/** Valid expense type categories. */
export const EXPENSE_TYPES = ["essentials", "desires", "savings"] as const;

/** Derived type from EXPENSE_TYPES constant. */
export type ExpenseType = (typeof EXPENSE_TYPES)[number];

/** Default budget split percentages (must sum to 100). */
export const DEFAULT_BUDGET_SPLIT = {
  essentials: 50,
  desires: 30,
  savings: 20,
} as const;

// Code generated by scripts/generate-currency-catalog.mjs; DO NOT EDIT.
export const SUPPORTED_CURRENCIES = [
  { code: "USD", symbol: "$", name: "US Dollar", minorUnitDigits: 2 },
  { code: "EUR", symbol: "€", name: "Euro", minorUnitDigits: 2 },
  { code: "GBP", symbol: "£", name: "British Pound", minorUnitDigits: 2 },
  { code: "JPY", symbol: "¥", name: "Japanese Yen", minorUnitDigits: 0 },
  { code: "CAD", symbol: "C$", name: "Canadian Dollar", minorUnitDigits: 2 },
  { code: "AUD", symbol: "A$", name: "Australian Dollar", minorUnitDigits: 2 },
  { code: "CHF", symbol: "CHF", name: "Swiss Franc", minorUnitDigits: 2 },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan", minorUnitDigits: 2 },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar", minorUnitDigits: 2 },
  { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar", minorUnitDigits: 2 },
] as const;

export type SupportedCurrency = (typeof SUPPORTED_CURRENCIES)[number];
export type SupportedCurrencyCode = SupportedCurrency["code"];
