// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/expense.proto

package expensepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExpenseData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ExpenseType         string                 `protobuf:"bytes,6,opt,name=expense_type,json=expenseType,proto3" json:"expense_type,omitempty"`
	TagId               string                 `protobuf:"bytes,7,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	ExpenseDate         string                 `protobuf:"bytes,8,opt,name=expense_date,json=expenseDate,proto3" json:"expense_date,omitempty"`
	PeriodYear          int32                  `protobuf:"varint,9,opt,name=period_year,json=periodYear,proto3" json:"period_year,omitempty"`
	PeriodMonth         int32                  `protobuf:"varint,10,opt,name=period_month,json=periodMonth,proto3" json:"period_month,omitempty"`
	Status              string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	CorrectsId          string                 `protobuf:"bytes,12,opt,name=corrects_id,json=correctsId,proto3" json:"corrects_id,omitempty"`
	IsProRata           bool                   `protobuf:"varint,13,opt,name=is_pro_rata,json=isProRata,proto3" json:"is_pro_rata,omitempty"`
	ProRataGroup        string                 `protobuf:"bytes,14,opt,name=pro_rata_group,json=proRataGroup,proto3" json:"pro_rata_group,omitempty"`
	ProRataIndex        int32                  `protobuf:"varint,15,opt,name=pro_rata_index,json=proRataIndex,proto3" json:"pro_rata_index,omitempty"`
	ProRataTotal        int32                  `protobuf:"varint,16,opt,name=pro_rata_total,json=proRataTotal,proto3" json:"pro_rata_total,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TransactionCurrency string                 `protobuf:"bytes,18,opt,name=transaction_currency,json=transactionCurrency,proto3" json:"transaction_currency,omitempty"`
	// Money snapshot fields.
	TransactionAmount     int64  `protobuf:"varint,20,opt,name=transaction_amount,json=transactionAmount,proto3" json:"transaction_amount,omitempty"`
	ReportingAmount       int64  `protobuf:"varint,21,opt,name=reporting_amount,json=reportingAmount,proto3" json:"reporting_amount,omitempty"`
	ReportingCurrency     string `protobuf:"bytes,22,opt,name=reporting_currency,json=reportingCurrency,proto3" json:"reporting_currency,omitempty"`
	ExchangeRate          string `protobuf:"bytes,23,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	ExchangeRateSource    string `protobuf:"bytes,24,opt,name=exchange_rate_source,json=exchangeRateSource,proto3" json:"exchange_rate_source,omitempty"`
	ExchangeRateTimestamp string `protobuf:"bytes,25,opt,name=exchange_rate_timestamp,json=exchangeRateTimestamp,proto3" json:"exchange_rate_timestamp,omitempty"`
	ExchangeRateExpiresAt string `protobuf:"bytes,26,opt,name=exchange_rate_expires_at,json=exchangeRateExpiresAt,proto3" json:"exchange_rate_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExpenseData) Reset() {
	*x = ExpenseData{}
	mi := &file_proto_expense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseData) ProtoMessage() {}

func (x *ExpenseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseData.ProtoReflect.Descriptor instead.
func (*ExpenseData) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{0}
}

func (x *ExpenseData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExpenseData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExpenseData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExpenseData) GetExpenseType() string {
	if x != nil {
		return x.ExpenseType
	}
	return ""
}

func (x *ExpenseData) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *ExpenseData) GetExpenseDate() string {
	if x != nil {
		return x.ExpenseDate
	}
	return ""
}

func (x *ExpenseData) GetPeriodYear() int32 {
	if x != nil {
		return x.PeriodYear
	}
	return 0
}

func (x *ExpenseData) GetPeriodMonth() int32 {
	if x != nil {
		return x.PeriodMonth
	}
	return 0
}

func (x *ExpenseData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExpenseData) GetCorrectsId() string {
	if x != nil {
		return x.CorrectsId
	}
	return ""
}

func (x *ExpenseData) GetIsProRata() bool {
	if x != nil {
		return x.IsProRata
	}
	return false
}

func (x *ExpenseData) GetProRataGroup() string {
	if x != nil {
		return x.ProRataGroup
	}
	return ""
}

func (x *ExpenseData) GetProRataIndex() int32 {
	if x != nil {
		return x.ProRataIndex
	}
	return 0
}

func (x *ExpenseData) GetProRataTotal() int32 {
	if x != nil {
		return x.ProRataTotal
	}
	return 0
}

func (x *ExpenseData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ExpenseData) GetTransactionCurrency() string {
	if x != nil {
		return x.TransactionCurrency
	}
	return ""
}

func (x *ExpenseData) GetTransactionAmount() int64 {
	if x != nil {
		return x.TransactionAmount
	}
	return 0
}

func (x *ExpenseData) GetReportingAmount() int64 {
	if x != nil {
		return x.ReportingAmount
	}
	return 0
}

func (x *ExpenseData) GetReportingCurrency() string {
	if x != nil {
		return x.ReportingCurrency
	}
	return ""
}

func (x *ExpenseData) GetExchangeRate() string {
	if x != nil {
		return x.ExchangeRate
	}
	return ""
}

func (x *ExpenseData) GetExchangeRateSource() string {
	if x != nil {
		return x.ExchangeRateSource
	}
	return ""
}

func (x *ExpenseData) GetExchangeRateTimestamp() string {
	if x != nil {
		return x.ExchangeRateTimestamp
	}
	return ""
}

func (x *ExpenseData) GetExchangeRateExpiresAt() string {
	if x != nil {
		return x.ExchangeRateExpiresAt
	}
	return ""
}

type CreateExpenseRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount              int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ExpenseType         string                 `protobuf:"bytes,5,opt,name=expense_type,json=expenseType,proto3" json:"expense_type,omitempty"`
	TagId               string                 `protobuf:"bytes,6,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	ExpenseDate         string                 `protobuf:"bytes,7,opt,name=expense_date,json=expenseDate,proto3" json:"expense_date,omitempty"`
	PeriodYear          int32                  `protobuf:"varint,8,opt,name=period_year,json=periodYear,proto3" json:"period_year,omitempty"`
	PeriodMonth         int32                  `protobuf:"varint,9,opt,name=period_month,json=periodMonth,proto3" json:"period_month,omitempty"`
	IsProRata           bool                   `protobuf:"varint,10,opt,name=is_pro_rata,json=isProRata,proto3" json:"is_pro_rata,omitempty"`
	ProRataGroup        string                 `protobuf:"bytes,11,opt,name=pro_rata_group,json=proRataGroup,proto3" json:"pro_rata_group,omitempty"`
	ProRataIndex        int32                  `protobuf:"varint,12,opt,name=pro_rata_index,json=proRataIndex,proto3" json:"pro_rata_index,omitempty"`
	ProRataTotal        int32                  `protobuf:"varint,13,opt,name=pro_rata_total,json=proRataTotal,proto3" json:"pro_rata_total,omitempty"`
	TransactionCurrency string                 `protobuf:"bytes,14,opt,name=transaction_currency,json=transactionCurrency,proto3" json:"transaction_currency,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateExpenseRequest) Reset() {
	*x = CreateExpenseRequest{}
	mi := &file_proto_expense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseRequest) ProtoMessage() {}

func (x *CreateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseRequest.ProtoReflect.Descriptor instead.
func (*CreateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExpenseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateExpenseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExpenseRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateExpenseRequest) GetExpenseType() string {
	if x != nil {
		return x.ExpenseType
	}
	return ""
}

func (x *CreateExpenseRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *CreateExpenseRequest) GetExpenseDate() string {
	if x != nil {
		return x.ExpenseDate
	}
	return ""
}

func (x *CreateExpenseRequest) GetPeriodYear() int32 {
	if x != nil {
		return x.PeriodYear
	}
	return 0
}

func (x *CreateExpenseRequest) GetPeriodMonth() int32 {
	if x != nil {
		return x.PeriodMonth
	}
	return 0
}

func (x *CreateExpenseRequest) GetIsProRata() bool {
	if x != nil {
		return x.IsProRata
	}
	return false
}

func (x *CreateExpenseRequest) GetProRataGroup() string {
	if x != nil {
		return x.ProRataGroup
	}
	return ""
}

func (x *CreateExpenseRequest) GetProRataIndex() int32 {
	if x != nil {
		return x.ProRataIndex
	}
	return 0
}

func (x *CreateExpenseRequest) GetProRataTotal() int32 {
	if x != nil {
		return x.ProRataTotal
	}
	return 0
}

func (x *CreateExpenseRequest) GetTransactionCurrency() string {
	if x != nil {
		return x.TransactionCurrency
	}
	return ""
}

type ExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expense       *ExpenseData           `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseResponse) Reset() {
	*x = ExpenseResponse{}
	mi := &file_proto_expense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseResponse) ProtoMessage() {}

func (x *ExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseResponse.ProtoReflect.Descriptor instead.
func (*ExpenseResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{2}
}

func (x *ExpenseResponse) GetExpense() *ExpenseData {
	if x != nil {
		return x.Expense
	}
	return nil
}

// TrustedPeriodContext is period context Finance resolved before asking Expense
// to write a pro-rata installment. Expense validates its consistency but does
// not call Finance again for Finance-originated pro-rata writes.
type TrustedPeriodContext struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeriodId          string                 `protobuf:"bytes,1,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year              int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Month             int32                  `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
	ReportingCurrency string                 `protobuf:"bytes,5,opt,name=reporting_currency,json=reportingCurrency,proto3" json:"reporting_currency,omitempty"`
	Source            string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrustedPeriodContext) Reset() {
	*x = TrustedPeriodContext{}
	mi := &file_proto_expense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustedPeriodContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustedPeriodContext) ProtoMessage() {}

func (x *TrustedPeriodContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustedPeriodContext.ProtoReflect.Descriptor instead.
func (*TrustedPeriodContext) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{3}
}

func (x *TrustedPeriodContext) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *TrustedPeriodContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrustedPeriodContext) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *TrustedPeriodContext) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *TrustedPeriodContext) GetReportingCurrency() string {
	if x != nil {
		return x.ReportingCurrency
	}
	return ""
}

func (x *TrustedPeriodContext) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// CapturedRateSnapshot is a full USD-based provider snapshot captured at
// pro-rata schedule creation. Future installments derive target reporting
// amounts from this snapshot instead of live rates.
type CapturedRateSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotVersion int32                  `protobuf:"varint,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	BaseCurrency    string                 `protobuf:"bytes,3,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	RateTimestamp   string                 `protobuf:"bytes,4,opt,name=rate_timestamp,json=rateTimestamp,proto3" json:"rate_timestamp,omitempty"`
	CapturedAt      string                 `protobuf:"bytes,5,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RatesByCurrency map[string]string      `protobuf:"bytes,7,rep,name=rates_by_currency,json=ratesByCurrency,proto3" json:"rates_by_currency,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapturedRateSnapshot) Reset() {
	*x = CapturedRateSnapshot{}
	mi := &file_proto_expense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturedRateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturedRateSnapshot) ProtoMessage() {}

func (x *CapturedRateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturedRateSnapshot.ProtoReflect.Descriptor instead.
func (*CapturedRateSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{4}
}

func (x *CapturedRateSnapshot) GetSnapshotVersion() int32 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

func (x *CapturedRateSnapshot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CapturedRateSnapshot) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *CapturedRateSnapshot) GetRateTimestamp() string {
	if x != nil {
		return x.RateTimestamp
	}
	return ""
}

func (x *CapturedRateSnapshot) GetCapturedAt() string {
	if x != nil {
		return x.CapturedAt
	}
	return ""
}

func (x *CapturedRateSnapshot) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CapturedRateSnapshot) GetRatesByCurrency() map[string]string {
	if x != nil {
		return x.RatesByCurrency
	}
	return nil
}

// CreateProRataInstallmentRequest is the Finance-originated internal write
// contract for the first (and future) pro-rata installments.
type CreateProRataInstallmentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PeriodContext        *TrustedPeriodContext  `protobuf:"bytes,2,opt,name=period_context,json=periodContext,proto3" json:"period_context,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionCurrency  string                 `protobuf:"bytes,5,opt,name=transaction_currency,json=transactionCurrency,proto3" json:"transaction_currency,omitempty"`
	ExpenseType          string                 `protobuf:"bytes,6,opt,name=expense_type,json=expenseType,proto3" json:"expense_type,omitempty"`
	TagId                string                 `protobuf:"bytes,7,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	ExpenseDate          string                 `protobuf:"bytes,8,opt,name=expense_date,json=expenseDate,proto3" json:"expense_date,omitempty"`
	ProRataGroup         string                 `protobuf:"bytes,9,opt,name=pro_rata_group,json=proRataGroup,proto3" json:"pro_rata_group,omitempty"`
	ProRataIndex         int32                  `protobuf:"varint,10,opt,name=pro_rata_index,json=proRataIndex,proto3" json:"pro_rata_index,omitempty"`
	ProRataTotal         int32                  `protobuf:"varint,11,opt,name=pro_rata_total,json=proRataTotal,proto3" json:"pro_rata_total,omitempty"`
	CapturedRateSnapshot *CapturedRateSnapshot  `protobuf:"bytes,12,opt,name=captured_rate_snapshot,json=capturedRateSnapshot,proto3" json:"captured_rate_snapshot,omitempty"`
	// legacy_migration marks a legacy pending pro-rata schedule that has no
	// captured snapshot. When true, Expense requires transaction_currency to
	// equal the period reporting currency and writes a migration snapshot
	// (exchangeRate = "1", exchangeRateSource = "migration") without calling FX.
	LegacyMigration bool `protobuf:"varint,13,opt,name=legacy_migration,json=legacyMigration,proto3" json:"legacy_migration,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateProRataInstallmentRequest) Reset() {
	*x = CreateProRataInstallmentRequest{}
	mi := &file_proto_expense_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProRataInstallmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProRataInstallmentRequest) ProtoMessage() {}

func (x *CreateProRataInstallmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProRataInstallmentRequest.ProtoReflect.Descriptor instead.
func (*CreateProRataInstallmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProRataInstallmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProRataInstallmentRequest) GetPeriodContext() *TrustedPeriodContext {
	if x != nil {
		return x.PeriodContext
	}
	return nil
}

func (x *CreateProRataInstallmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProRataInstallmentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateProRataInstallmentRequest) GetTransactionCurrency() string {
	if x != nil {
		return x.TransactionCurrency
	}
	return ""
}

func (x *CreateProRataInstallmentRequest) GetExpenseType() string {
	if x != nil {
		return x.ExpenseType
	}
	return ""
}

func (x *CreateProRataInstallmentRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *CreateProRataInstallmentRequest) GetExpenseDate() string {
	if x != nil {
		return x.ExpenseDate
	}
	return ""
}

func (x *CreateProRataInstallmentRequest) GetProRataGroup() string {
	if x != nil {
		return x.ProRataGroup
	}
	return ""
}

func (x *CreateProRataInstallmentRequest) GetProRataIndex() int32 {
	if x != nil {
		return x.ProRataIndex
	}
	return 0
}

func (x *CreateProRataInstallmentRequest) GetProRataTotal() int32 {
	if x != nil {
		return x.ProRataTotal
	}
	return 0
}

func (x *CreateProRataInstallmentRequest) GetCapturedRateSnapshot() *CapturedRateSnapshot {
	if x != nil {
		return x.CapturedRateSnapshot
	}
	return nil
}

func (x *CreateProRataInstallmentRequest) GetLegacyMigration() bool {
	if x != nil {
		return x.LegacyMigration
	}
	return false
}

type GetExpensesForPeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpensesForPeriodRequest) Reset() {
	*x = GetExpensesForPeriodRequest{}
	mi := &file_proto_expense_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpensesForPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpensesForPeriodRequest) ProtoMessage() {}

func (x *GetExpensesForPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpensesForPeriodRequest.ProtoReflect.Descriptor instead.
func (*GetExpensesForPeriodRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{6}
}

func (x *GetExpensesForPeriodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetExpensesForPeriodRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetExpensesForPeriodRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GetExpensesForPeriodRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExpensesForPeriodRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ExpenseListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ExpenseData         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseListResponse) Reset() {
	*x = ExpenseListResponse{}
	mi := &file_proto_expense_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseListResponse) ProtoMessage() {}

func (x *ExpenseListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseListResponse.ProtoReflect.Descriptor instead.
func (*ExpenseListResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{7}
}

func (x *ExpenseListResponse) GetData() []*ExpenseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExpenseListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ExpenseListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ExpenseListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ExpenseListResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpenseRequest) Reset() {
	*x = GetExpenseRequest{}
	mi := &file_proto_expense_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpenseRequest) ProtoMessage() {}

func (x *GetExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpenseRequest.ProtoReflect.Descriptor instead.
func (*GetExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{8}
}

func (x *GetExpenseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetExpenseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CorrectExpenseRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ExpenseId           string                 `protobuf:"bytes,1,opt,name=expense_id,json=expenseId,proto3" json:"expense_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount              int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	ExpenseType         string                 `protobuf:"bytes,5,opt,name=expense_type,json=expenseType,proto3" json:"expense_type,omitempty"`
	TagId               string                 `protobuf:"bytes,6,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	ExpenseDate         string                 `protobuf:"bytes,7,opt,name=expense_date,json=expenseDate,proto3" json:"expense_date,omitempty"`
	TransactionCurrency string                 `protobuf:"bytes,8,opt,name=transaction_currency,json=transactionCurrency,proto3" json:"transaction_currency,omitempty"`
	Currency            string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"` // Deprecated alias during rollout.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CorrectExpenseRequest) Reset() {
	*x = CorrectExpenseRequest{}
	mi := &file_proto_expense_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrectExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrectExpenseRequest) ProtoMessage() {}

func (x *CorrectExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrectExpenseRequest.ProtoReflect.Descriptor instead.
func (*CorrectExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{9}
}

func (x *CorrectExpenseRequest) GetExpenseId() string {
	if x != nil {
		return x.ExpenseId
	}
	return ""
}

func (x *CorrectExpenseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CorrectExpenseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CorrectExpenseRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CorrectExpenseRequest) GetExpenseType() string {
	if x != nil {
		return x.ExpenseType
	}
	return ""
}

func (x *CorrectExpenseRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *CorrectExpenseRequest) GetExpenseDate() string {
	if x != nil {
		return x.ExpenseDate
	}
	return ""
}

func (x *CorrectExpenseRequest) GetTransactionCurrency() string {
	if x != nil {
		return x.TransactionCurrency
	}
	return ""
}

func (x *CorrectExpenseRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetCorrectionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpenseId     string                 `protobuf:"bytes,1,opt,name=expense_id,json=expenseId,proto3" json:"expense_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCorrectionHistoryRequest) Reset() {
	*x = GetCorrectionHistoryRequest{}
	mi := &file_proto_expense_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCorrectionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCorrectionHistoryRequest) ProtoMessage() {}

func (x *GetCorrectionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCorrectionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetCorrectionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{10}
}

func (x *GetCorrectionHistoryRequest) GetExpenseId() string {
	if x != nil {
		return x.ExpenseId
	}
	return ""
}

type CorrectionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ExpenseData         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrectionHistoryResponse) Reset() {
	*x = CorrectionHistoryResponse{}
	mi := &file_proto_expense_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrectionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrectionHistoryResponse) ProtoMessage() {}

func (x *CorrectionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrectionHistoryResponse.ProtoReflect.Descriptor instead.
func (*CorrectionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{11}
}

func (x *CorrectionHistoryResponse) GetEntries() []*ExpenseData {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetProRataGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProRataGroupRequest) Reset() {
	*x = GetProRataGroupRequest{}
	mi := &file_proto_expense_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProRataGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProRataGroupRequest) ProtoMessage() {}

func (x *GetProRataGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProRataGroupRequest.ProtoReflect.Descriptor instead.
func (*GetProRataGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{12}
}

func (x *GetProRataGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type StreamAllUserExpensesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // internal server-side keyset page size; 0 = server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAllUserExpensesRequest) Reset() {
	*x = StreamAllUserExpensesRequest{}
	mi := &file_proto_expense_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAllUserExpensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAllUserExpensesRequest) ProtoMessage() {}

func (x *StreamAllUserExpensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAllUserExpensesRequest.ProtoReflect.Descriptor instead.
func (*StreamAllUserExpensesRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{13}
}

func (x *StreamAllUserExpensesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamAllUserExpensesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CountExpensesByTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         string                 `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountExpensesByTagRequest) Reset() {
	*x = CountExpensesByTagRequest{}
	mi := &file_proto_expense_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountExpensesByTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountExpensesByTagRequest) ProtoMessage() {}

func (x *CountExpensesByTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountExpensesByTagRequest.ProtoReflect.Descriptor instead.
func (*CountExpensesByTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{14}
}

func (x *CountExpensesByTagRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *CountExpensesByTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CountExpensesByTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountExpensesByTagResponse) Reset() {
	*x = CountExpensesByTagResponse{}
	mi := &file_proto_expense_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountExpensesByTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountExpensesByTagResponse) ProtoMessage() {}

func (x *CountExpensesByTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountExpensesByTagResponse.ProtoReflect.Descriptor instead.
func (*CountExpensesByTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{15}
}

func (x *CountExpensesByTagResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AnonymizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymizeRequest) Reset() {
	*x = AnonymizeRequest{}
	mi := &file_proto_expense_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymizeRequest) ProtoMessage() {}

func (x *AnonymizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymizeRequest.ProtoReflect.Descriptor instead.
func (*AnonymizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{16}
}

func (x *AnonymizeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AnonymizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymizeResponse) Reset() {
	*x = AnonymizeResponse{}
	mi := &file_proto_expense_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymizeResponse) ProtoMessage() {}

func (x *AnonymizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymizeResponse.ProtoReflect.Descriptor instead.
func (*AnonymizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_proto_rawDescGZIP(), []int{17}
}

var File_proto_expense_proto protoreflect.FileDescriptor

const file_proto_expense_proto_rawDesc = "" +
	"\n" +
	"\x13proto/expense.proto\x12\aexpense\"\xe5\x06\n" +
	"\vExpenseData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fexpense_type\x18\x06 \x01(\tR\vexpenseType\x12\x15\n" +
	"\x06tag_id\x18\a \x01(\tR\x05tagId\x12!\n" +
	"\fexpense_date\x18\b \x01(\tR\vexpenseDate\x12\x1f\n" +
	"\vperiod_year\x18\t \x01(\x05R\n" +
	"periodYear\x12!\n" +
	"\fperiod_month\x18\n" +
	" \x01(\x05R\vperiodMonth\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1f\n" +
	"\vcorrects_id\x18\f \x01(\tR\n" +
	"correctsId\x12\x1e\n" +
	"\vis_pro_rata\x18\r \x01(\bR\tisProRata\x12$\n" +
	"\x0epro_rata_group\x18\x0e \x01(\tR\fproRataGroup\x12$\n" +
	"\x0epro_rata_index\x18\x0f \x01(\x05R\fproRataIndex\x12$\n" +
	"\x0epro_rata_total\x18\x10 \x01(\x05R\fproRataTotal\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x121\n" +
	"\x14transaction_currency\x18\x12 \x01(\tR\x13transactionCurrency\x12-\n" +
	"\x12transaction_amount\x18\x14 \x01(\x03R\x11transactionAmount\x12)\n" +
	"\x10reporting_amount\x18\x15 \x01(\x03R\x0freportingAmount\x12-\n" +
	"\x12reporting_currency\x18\x16 \x01(\tR\x11reportingCurrency\x12#\n" +
	"\rexchange_rate\x18\x17 \x01(\tR\fexchangeRate\x120\n" +
	"\x14exchange_rate_source\x18\x18 \x01(\tR\x12exchangeRateSource\x126\n" +
	"\x17exchange_rate_timestamp\x18\x19 \x01(\tR\x15exchangeRateTimestamp\x127\n" +
	"\x18exchange_rate_expires_at\x18\x1a \x01(\tR\x15exchangeRateExpiresAtJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06\"\xc7\x03\n" +
	"\x14CreateExpenseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12!\n" +
	"\fexpense_type\x18\x05 \x01(\tR\vexpenseType\x12\x15\n" +
	"\x06tag_id\x18\x06 \x01(\tR\x05tagId\x12!\n" +
	"\fexpense_date\x18\a \x01(\tR\vexpenseDate\x12\x1f\n" +
	"\vperiod_year\x18\b \x01(\x05R\n" +
	"periodYear\x12!\n" +
	"\fperiod_month\x18\t \x01(\x05R\vperiodMonth\x12\x1e\n" +
	"\vis_pro_rata\x18\n" +
	" \x01(\bR\tisProRata\x12$\n" +
	"\x0epro_rata_group\x18\v \x01(\tR\fproRataGroup\x12$\n" +
	"\x0epro_rata_index\x18\f \x01(\x05R\fproRataIndex\x12$\n" +
	"\x0epro_rata_total\x18\r \x01(\x05R\fproRataTotal\x121\n" +
	"\x14transaction_currency\x18\x0e \x01(\tR\x13transactionCurrencyJ\x04\b\x04\x10\x05\"A\n" +
	"\x0fExpenseResponse\x12.\n" +
	"\aexpense\x18\x01 \x01(\v2\x14.expense.ExpenseDataR\aexpense\"\xbd\x01\n" +
	"\x14TrustedPeriodContext\x12\x1b\n" +
	"\tperiod_id\x18\x01 \x01(\tR\bperiodId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x04 \x01(\x05R\x05month\x12-\n" +
	"\x12reporting_currency\x18\x05 \x01(\tR\x11reportingCurrency\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"\x89\x03\n" +
	"\x14CapturedRateSnapshot\x12)\n" +
	"\x10snapshot_version\x18\x01 \x01(\x05R\x0fsnapshotVersion\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12#\n" +
	"\rbase_currency\x18\x03 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0erate_timestamp\x18\x04 \x01(\tR\rrateTimestamp\x12\x1f\n" +
	"\vcaptured_at\x18\x05 \x01(\tR\n" +
	"capturedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\x12^\n" +
	"\x11rates_by_currency\x18\a \x03(\v22.expense.CapturedRateSnapshot.RatesByCurrencyEntryR\x0fratesByCurrency\x1aB\n" +
	"\x14RatesByCurrencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x04\n" +
	"\x1fCreateProRataInstallmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12D\n" +
	"\x0eperiod_context\x18\x02 \x01(\v2\x1d.expense.TrustedPeriodContextR\rperiodContext\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x121\n" +
	"\x14transaction_currency\x18\x05 \x01(\tR\x13transactionCurrency\x12!\n" +
	"\fexpense_type\x18\x06 \x01(\tR\vexpenseType\x12\x15\n" +
	"\x06tag_id\x18\a \x01(\tR\x05tagId\x12!\n" +
	"\fexpense_date\x18\b \x01(\tR\vexpenseDate\x12$\n" +
	"\x0epro_rata_group\x18\t \x01(\tR\fproRataGroup\x12$\n" +
	"\x0epro_rata_index\x18\n" +
	" \x01(\x05R\fproRataIndex\x12$\n" +
	"\x0epro_rata_total\x18\v \x01(\x05R\fproRataTotal\x12S\n" +
	"\x16captured_rate_snapshot\x18\f \x01(\v2\x1d.expense.CapturedRateSnapshotR\x14capturedRateSnapshot\x12)\n" +
	"\x10legacy_migration\x18\r \x01(\bR\x0flegacyMigration\"\x91\x01\n" +
	"\x1bGetExpensesForPeriodRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xa1\x01\n" +
	"\x13ExpenseListResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.expense.ExpenseDataR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"<\n" +
	"\x11GetExpenseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xa7\x02\n" +
	"\x15CorrectExpenseRequest\x12\x1d\n" +
	"\n" +
	"expense_id\x18\x01 \x01(\tR\texpenseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12!\n" +
	"\fexpense_type\x18\x05 \x01(\tR\vexpenseType\x12\x15\n" +
	"\x06tag_id\x18\x06 \x01(\tR\x05tagId\x12!\n" +
	"\fexpense_date\x18\a \x01(\tR\vexpenseDate\x121\n" +
	"\x14transaction_currency\x18\b \x01(\tR\x13transactionCurrency\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\"<\n" +
	"\x1bGetCorrectionHistoryRequest\x12\x1d\n" +
	"\n" +
	"expense_id\x18\x01 \x01(\tR\texpenseId\"K\n" +
	"\x19CorrectionHistoryResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.expense.ExpenseDataR\aentries\"3\n" +
	"\x16GetProRataGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"T\n" +
	"\x1cStreamAllUserExpensesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"K\n" +
	"\x19CountExpensesByTagRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\tR\x05tagId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"2\n" +
	"\x1aCountExpensesByTagResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"+\n" +
	"\x10AnonymizeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x13\n" +
	"\x11AnonymizeResponse2\xb0\x05\n" +
	"\x0eExpenseService\x12H\n" +
	"\rCreateExpense\x12\x1d.expense.CreateExpenseRequest\x1a\x18.expense.ExpenseResponse\x12^\n" +
	"\x18CreateProRataInstallment\x12(.expense.CreateProRataInstallmentRequest\x1a\x18.expense.ExpenseResponse\x12Z\n" +
	"\x14GetExpensesForPeriod\x12$.expense.GetExpensesForPeriodRequest\x1a\x1c.expense.ExpenseListResponse\x12B\n" +
	"\n" +
	"GetExpense\x12\x1a.expense.GetExpenseRequest\x1a\x18.expense.ExpenseResponse\x12]\n" +
	"\x12CountExpensesByTag\x12\".expense.CountExpensesByTagRequest\x1a#.expense.CountExpensesByTagResponse\x12V\n" +
	"\x15StreamAllUserExpenses\x12%.expense.StreamAllUserExpensesRequest\x1a\x14.expense.ExpenseData0\x01\x12Q\n" +
	"\x18AnonymizeAllUserExpenses\x12\x19.expense.AnonymizeRequest\x1a\x1a.expense.AnonymizeResponse\x12J\n" +
	"\x0eCorrectExpense\x12\x1e.expense.CorrectExpenseRequest\x1a\x18.expense.ExpenseResponseB?Z=github.com/ItsThompson/gofin/services/expense/proto/expensepbb\x06proto3"

var (
	file_proto_expense_proto_rawDescOnce sync.Once
	file_proto_expense_proto_rawDescData []byte
)

func file_proto_expense_proto_rawDescGZIP() []byte {
	file_proto_expense_proto_rawDescOnce.Do(func() {
		file_proto_expense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_expense_proto_rawDesc), len(file_proto_expense_proto_rawDesc)))
	})
	return file_proto_expense_proto_rawDescData
}

var file_proto_expense_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_expense_proto_goTypes = []any{
	(*ExpenseData)(nil),                     // 0: expense.ExpenseData
	(*CreateExpenseRequest)(nil),            // 1: expense.CreateExpenseRequest
	(*ExpenseResponse)(nil),                 // 2: expense.ExpenseResponse
	(*TrustedPeriodContext)(nil),            // 3: expense.TrustedPeriodContext
	(*CapturedRateSnapshot)(nil),            // 4: expense.CapturedRateSnapshot
	(*CreateProRataInstallmentRequest)(nil), // 5: expense.CreateProRataInstallmentRequest
	(*GetExpensesForPeriodRequest)(nil),     // 6: expense.GetExpensesForPeriodRequest
	(*ExpenseListResponse)(nil),             // 7: expense.ExpenseListResponse
	(*GetExpenseRequest)(nil),               // 8: expense.GetExpenseRequest
	(*CorrectExpenseRequest)(nil),           // 9: expense.CorrectExpenseRequest
	(*GetCorrectionHistoryRequest)(nil),     // 10: expense.GetCorrectionHistoryRequest
	(*CorrectionHistoryResponse)(nil),       // 11: expense.CorrectionHistoryResponse
	(*GetProRataGroupRequest)(nil),          // 12: expense.GetProRataGroupRequest
	(*StreamAllUserExpensesRequest)(nil),    // 13: expense.StreamAllUserExpensesRequest
	(*CountExpensesByTagRequest)(nil),       // 14: expense.CountExpensesByTagRequest
	(*CountExpensesByTagResponse)(nil),      // 15: expense.CountExpensesByTagResponse
	(*AnonymizeRequest)(nil),                // 16: expense.AnonymizeRequest
	(*AnonymizeResponse)(nil),               // 17: expense.AnonymizeResponse
	nil,                                     // 18: expense.CapturedRateSnapshot.RatesByCurrencyEntry
}
var file_proto_expense_proto_depIdxs = []int32{
	0,  // 0: expense.ExpenseResponse.expense:type_name -> expense.ExpenseData
	18, // 1: expense.CapturedRateSnapshot.rates_by_currency:type_name -> expense.CapturedRateSnapshot.RatesByCurrencyEntry
	3,  // 2: expense.CreateProRataInstallmentRequest.period_context:type_name -> expense.TrustedPeriodContext
	4,  // 3: expense.CreateProRataInstallmentRequest.captured_rate_snapshot:type_name -> expense.CapturedRateSnapshot
	0,  // 4: expense.ExpenseListResponse.data:type_name -> expense.ExpenseData
	0,  // 5: expense.CorrectionHistoryResponse.entries:type_name -> expense.ExpenseData
	1,  // 6: expense.ExpenseService.CreateExpense:input_type -> expense.CreateExpenseRequest
	5,  // 7: expense.ExpenseService.CreateProRataInstallment:input_type -> expense.CreateProRataInstallmentRequest
	6,  // 8: expense.ExpenseService.GetExpensesForPeriod:input_type -> expense.GetExpensesForPeriodRequest
	8,  // 9: expense.ExpenseService.GetExpense:input_type -> expense.GetExpenseRequest
	14, // 10: expense.ExpenseService.CountExpensesByTag:input_type -> expense.CountExpensesByTagRequest
	13, // 11: expense.ExpenseService.StreamAllUserExpenses:input_type -> expense.StreamAllUserExpensesRequest
	16, // 12: expense.ExpenseService.AnonymizeAllUserExpenses:input_type -> expense.AnonymizeRequest
	9,  // 13: expense.ExpenseService.CorrectExpense:input_type -> expense.CorrectExpenseRequest
	2,  // 14: expense.ExpenseService.CreateExpense:output_type -> expense.ExpenseResponse
	2,  // 15: expense.ExpenseService.CreateProRataInstallment:output_type -> expense.ExpenseResponse
	7,  // 16: expense.ExpenseService.GetExpensesForPeriod:output_type -> expense.ExpenseListResponse
	2,  // 17: expense.ExpenseService.GetExpense:output_type -> expense.ExpenseResponse
	15, // 18: expense.ExpenseService.CountExpensesByTag:output_type -> expense.CountExpensesByTagResponse
	0,  // 19: expense.ExpenseService.StreamAllUserExpenses:output_type -> expense.ExpenseData
	17, // 20: expense.ExpenseService.AnonymizeAllUserExpenses:output_type -> expense.AnonymizeResponse
	2,  // 21: expense.ExpenseService.CorrectExpense:output_type -> expense.ExpenseResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_expense_proto_init() }
func file_proto_expense_proto_init() {
	if File_proto_expense_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_expense_proto_rawDesc), len(file_proto_expense_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_expense_proto_goTypes,
		DependencyIndexes: file_proto_expense_proto_depIdxs,
		MessageInfos:      file_proto_expense_proto_msgTypes,
	}.Build()
	File_proto_expense_proto = out.File
	file_proto_expense_proto_goTypes = nil
	file_proto_expense_proto_depIdxs = nil
}
