// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/expense.proto

package expensepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExpenseService_CreateExpense_FullMethodName            = "/expense.ExpenseService/CreateExpense"
	ExpenseService_GetExpensesForPeriod_FullMethodName     = "/expense.ExpenseService/GetExpensesForPeriod"
	ExpenseService_GetExpense_FullMethodName               = "/expense.ExpenseService/GetExpense"
	ExpenseService_CountExpensesByTag_FullMethodName       = "/expense.ExpenseService/CountExpensesByTag"
	ExpenseService_StreamAllUserExpenses_FullMethodName    = "/expense.ExpenseService/StreamAllUserExpenses"
	ExpenseService_AnonymizeAllUserExpenses_FullMethodName = "/expense.ExpenseService/AnonymizeAllUserExpenses"
	ExpenseService_CorrectExpense_FullMethodName           = "/expense.ExpenseService/CorrectExpense"
	ExpenseService_GetCorrectionHistory_FullMethodName     = "/expense.ExpenseService/GetCorrectionHistory"
	ExpenseService_GetProRataGroup_FullMethodName          = "/expense.ExpenseService/GetProRataGroup"
)

// ExpenseServiceClient is the client API for ExpenseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExpenseServiceClient interface {
	// Implemented in this ticket
	CreateExpense(ctx context.Context, in *CreateExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error)
	GetExpensesForPeriod(ctx context.Context, in *GetExpensesForPeriodRequest, opts ...grpc.CallOption) (*ExpenseListResponse, error)
	GetExpense(ctx context.Context, in *GetExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error)
	// Tag usage check (called by finance service during tag deletion)
	CountExpensesByTag(ctx context.Context, in *CountExpensesByTagRequest, opts ...grpc.CallOption) (*CountExpensesByTagResponse, error)
	// Data export streaming: the server streams every expense (active + corrected)
	// for a user in chronological order (created_at ASC, id ASC). The server pages
	// internally with a keyset cursor, bounding server memory to O(page_size); the
	// client writes rows incrementally.
	StreamAllUserExpenses(ctx context.Context, in *StreamAllUserExpensesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExpenseData], error)
	// GDPR: anonymize all expenses for a user (field redaction, not deletion)
	AnonymizeAllUserExpenses(ctx context.Context, in *AnonymizeRequest, opts ...grpc.CallOption) (*AnonymizeResponse, error)
	// Stubs: implemented in later tickets
	CorrectExpense(ctx context.Context, in *CorrectExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error)
	GetCorrectionHistory(ctx context.Context, in *GetCorrectionHistoryRequest, opts ...grpc.CallOption) (*CorrectionHistoryResponse, error)
	GetProRataGroup(ctx context.Context, in *GetProRataGroupRequest, opts ...grpc.CallOption) (*ExpenseListResponse, error)
}

type expenseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExpenseServiceClient(cc grpc.ClientConnInterface) ExpenseServiceClient {
	return &expenseServiceClient{cc}
}

func (c *expenseServiceClient) CreateExpense(ctx context.Context, in *CreateExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpenseResponse)
	err := c.cc.Invoke(ctx, ExpenseService_CreateExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) GetExpensesForPeriod(ctx context.Context, in *GetExpensesForPeriodRequest, opts ...grpc.CallOption) (*ExpenseListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpenseListResponse)
	err := c.cc.Invoke(ctx, ExpenseService_GetExpensesForPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) GetExpense(ctx context.Context, in *GetExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpenseResponse)
	err := c.cc.Invoke(ctx, ExpenseService_GetExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) CountExpensesByTag(ctx context.Context, in *CountExpensesByTagRequest, opts ...grpc.CallOption) (*CountExpensesByTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountExpensesByTagResponse)
	err := c.cc.Invoke(ctx, ExpenseService_CountExpensesByTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) StreamAllUserExpenses(ctx context.Context, in *StreamAllUserExpensesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExpenseData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExpenseService_ServiceDesc.Streams[0], ExpenseService_StreamAllUserExpenses_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAllUserExpensesRequest, ExpenseData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExpenseService_StreamAllUserExpensesClient = grpc.ServerStreamingClient[ExpenseData]

func (c *expenseServiceClient) AnonymizeAllUserExpenses(ctx context.Context, in *AnonymizeRequest, opts ...grpc.CallOption) (*AnonymizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnonymizeResponse)
	err := c.cc.Invoke(ctx, ExpenseService_AnonymizeAllUserExpenses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) CorrectExpense(ctx context.Context, in *CorrectExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpenseResponse)
	err := c.cc.Invoke(ctx, ExpenseService_CorrectExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) GetCorrectionHistory(ctx context.Context, in *GetCorrectionHistoryRequest, opts ...grpc.CallOption) (*CorrectionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CorrectionHistoryResponse)
	err := c.cc.Invoke(ctx, ExpenseService_GetCorrectionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) GetProRataGroup(ctx context.Context, in *GetProRataGroupRequest, opts ...grpc.CallOption) (*ExpenseListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpenseListResponse)
	err := c.cc.Invoke(ctx, ExpenseService_GetProRataGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExpenseServiceServer is the server API for ExpenseService service.
// All implementations must embed UnimplementedExpenseServiceServer
// for forward compatibility.
type ExpenseServiceServer interface {
	// Implemented in this ticket
	CreateExpense(context.Context, *CreateExpenseRequest) (*ExpenseResponse, error)
	GetExpensesForPeriod(context.Context, *GetExpensesForPeriodRequest) (*ExpenseListResponse, error)
	GetExpense(context.Context, *GetExpenseRequest) (*ExpenseResponse, error)
	// Tag usage check (called by finance service during tag deletion)
	CountExpensesByTag(context.Context, *CountExpensesByTagRequest) (*CountExpensesByTagResponse, error)
	// Data export streaming: the server streams every expense (active + corrected)
	// for a user in chronological order (created_at ASC, id ASC). The server pages
	// internally with a keyset cursor, bounding server memory to O(page_size); the
	// client writes rows incrementally.
	StreamAllUserExpenses(*StreamAllUserExpensesRequest, grpc.ServerStreamingServer[ExpenseData]) error
	// GDPR: anonymize all expenses for a user (field redaction, not deletion)
	AnonymizeAllUserExpenses(context.Context, *AnonymizeRequest) (*AnonymizeResponse, error)
	// Stubs: implemented in later tickets
	CorrectExpense(context.Context, *CorrectExpenseRequest) (*ExpenseResponse, error)
	GetCorrectionHistory(context.Context, *GetCorrectionHistoryRequest) (*CorrectionHistoryResponse, error)
	GetProRataGroup(context.Context, *GetProRataGroupRequest) (*ExpenseListResponse, error)
	mustEmbedUnimplementedExpenseServiceServer()
}

// UnimplementedExpenseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExpenseServiceServer struct{}

func (UnimplementedExpenseServiceServer) CreateExpense(context.Context, *CreateExpenseRequest) (*ExpenseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExpense not implemented")
}
func (UnimplementedExpenseServiceServer) GetExpensesForPeriod(context.Context, *GetExpensesForPeriodRequest) (*ExpenseListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpensesForPeriod not implemented")
}
func (UnimplementedExpenseServiceServer) GetExpense(context.Context, *GetExpenseRequest) (*ExpenseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpense not implemented")
}
func (UnimplementedExpenseServiceServer) CountExpensesByTag(context.Context, *CountExpensesByTagRequest) (*CountExpensesByTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountExpensesByTag not implemented")
}
func (UnimplementedExpenseServiceServer) StreamAllUserExpenses(*StreamAllUserExpensesRequest, grpc.ServerStreamingServer[ExpenseData]) error {
	return status.Error(codes.Unimplemented, "method StreamAllUserExpenses not implemented")
}
func (UnimplementedExpenseServiceServer) AnonymizeAllUserExpenses(context.Context, *AnonymizeRequest) (*AnonymizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnonymizeAllUserExpenses not implemented")
}
func (UnimplementedExpenseServiceServer) CorrectExpense(context.Context, *CorrectExpenseRequest) (*ExpenseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CorrectExpense not implemented")
}
func (UnimplementedExpenseServiceServer) GetCorrectionHistory(context.Context, *GetCorrectionHistoryRequest) (*CorrectionHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCorrectionHistory not implemented")
}
func (UnimplementedExpenseServiceServer) GetProRataGroup(context.Context, *GetProRataGroupRequest) (*ExpenseListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProRataGroup not implemented")
}
func (UnimplementedExpenseServiceServer) mustEmbedUnimplementedExpenseServiceServer() {}
func (UnimplementedExpenseServiceServer) testEmbeddedByValue()                        {}

// UnsafeExpenseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExpenseServiceServer will
// result in compilation errors.
type UnsafeExpenseServiceServer interface {
	mustEmbedUnimplementedExpenseServiceServer()
}

func RegisterExpenseServiceServer(s grpc.ServiceRegistrar, srv ExpenseServiceServer) {
	// If the following call panics, it indicates UnimplementedExpenseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExpenseService_ServiceDesc, srv)
}

func _ExpenseService_CreateExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).CreateExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpenseService_CreateExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).CreateExpense(ctx, req.(*CreateExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_GetExpensesForPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpensesForPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetExpensesForPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpenseService_GetExpensesForPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetExpensesForPeriod(ctx, req.(*GetExpensesForPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_GetExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpenseService_GetExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetExpense(ctx, req.(*GetExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_CountExpensesByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountExpensesByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).CountExpensesByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpenseService_CountExpensesByTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).CountExpensesByTag(ctx, req.(*CountExpensesByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_StreamAllUserExpenses_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAllUserExpensesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExpenseServiceServer).StreamAllUserExpenses(m, &grpc.GenericServerStream[StreamAllUserExpensesRequest, ExpenseData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExpenseService_StreamAllUserExpensesServer = grpc.ServerStreamingServer[ExpenseData]

func _ExpenseService_AnonymizeAllUserExpenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnonymizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).AnonymizeAllUserExpenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpenseService_AnonymizeAllUserExpenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).AnonymizeAllUserExpenses(ctx, req.(*AnonymizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_CorrectExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorrectExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).CorrectExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpenseService_CorrectExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).CorrectExpense(ctx, req.(*CorrectExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_GetCorrectionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCorrectionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetCorrectionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpenseService_GetCorrectionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetCorrectionHistory(ctx, req.(*GetCorrectionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_GetProRataGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProRataGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetProRataGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpenseService_GetProRataGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetProRataGroup(ctx, req.(*GetProRataGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExpenseService_ServiceDesc is the grpc.ServiceDesc for ExpenseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExpenseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "expense.ExpenseService",
	HandlerType: (*ExpenseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExpense",
			Handler:    _ExpenseService_CreateExpense_Handler,
		},
		{
			MethodName: "GetExpensesForPeriod",
			Handler:    _ExpenseService_GetExpensesForPeriod_Handler,
		},
		{
			MethodName: "GetExpense",
			Handler:    _ExpenseService_GetExpense_Handler,
		},
		{
			MethodName: "CountExpensesByTag",
			Handler:    _ExpenseService_CountExpensesByTag_Handler,
		},
		{
			MethodName: "AnonymizeAllUserExpenses",
			Handler:    _ExpenseService_AnonymizeAllUserExpenses_Handler,
		},
		{
			MethodName: "CorrectExpense",
			Handler:    _ExpenseService_CorrectExpense_Handler,
		},
		{
			MethodName: "GetCorrectionHistory",
			Handler:    _ExpenseService_GetCorrectionHistory_Handler,
		},
		{
			MethodName: "GetProRataGroup",
			Handler:    _ExpenseService_GetProRataGroup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAllUserExpenses",
			Handler:       _ExpenseService_StreamAllUserExpenses_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/expense.proto",
}
