// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: proto/datarights.proto

package datarightspb

import (
	reportingpb "github.com/ItsThompson/gofin/services/shared/reporting/proto/reportingpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExportMetricsRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	WindowSet     *reportingpb.ReportWindowSet `protobuf:"bytes,1,opt,name=window_set,json=windowSet,proto3" json:"window_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportMetricsRequest) Reset() {
	*x = GetExportMetricsRequest{}
	mi := &file_proto_datarights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportMetricsRequest) ProtoMessage() {}

func (x *GetExportMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datarights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetExportMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_datarights_proto_rawDescGZIP(), []int{0}
}

func (x *GetExportMetricsRequest) GetWindowSet() *reportingpb.ReportWindowSet {
	if x != nil {
		return x.WindowSet
	}
	return nil
}

type ExportMetricsResponse struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	WindowSet        *reportingpb.ReportWindowSet `protobuf:"bytes,1,opt,name=window_set,json=windowSet,proto3" json:"window_set,omitempty"`
	CompletedExports *reportingpb.CountResult     `protobuf:"bytes,2,opt,name=completed_exports,json=completedExports,proto3" json:"completed_exports,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExportMetricsResponse) Reset() {
	*x = ExportMetricsResponse{}
	mi := &file_proto_datarights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMetricsResponse) ProtoMessage() {}

func (x *ExportMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datarights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMetricsResponse.ProtoReflect.Descriptor instead.
func (*ExportMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_datarights_proto_rawDescGZIP(), []int{1}
}

func (x *ExportMetricsResponse) GetWindowSet() *reportingpb.ReportWindowSet {
	if x != nil {
		return x.WindowSet
	}
	return nil
}

func (x *ExportMetricsResponse) GetCompletedExports() *reportingpb.CountResult {
	if x != nil {
		return x.CompletedExports
	}
	return nil
}

var File_proto_datarights_proto protoreflect.FileDescriptor

const file_proto_datarights_proto_rawDesc = "" +
	"\n" +
	"\x16proto/datarights.proto\x12\n" +
	"datarights\x1a&shared/reporting/proto/reporting.proto\"T\n" +
	"\x17GetExportMetricsRequest\x129\n" +
	"\n" +
	"window_set\x18\x01 \x01(\v2\x1a.reporting.ReportWindowSetR\twindowSet\"\x97\x01\n" +
	"\x15ExportMetricsResponse\x129\n" +
	"\n" +
	"window_set\x18\x01 \x01(\v2\x1a.reporting.ReportWindowSetR\twindowSet\x12C\n" +
	"\x11completed_exports\x18\x02 \x01(\v2\x16.reporting.CountResultR\x10completedExports2o\n" +
	"\x11DatarightsService\x12Z\n" +
	"\x10GetExportMetrics\x12#.datarights.GetExportMetricsRequest\x1a!.datarights.ExportMetricsResponseBEZCgithub.com/ItsThompson/gofin/services/datarights/proto/datarightspbb\x06proto3"

var (
	file_proto_datarights_proto_rawDescOnce sync.Once
	file_proto_datarights_proto_rawDescData []byte
)

func file_proto_datarights_proto_rawDescGZIP() []byte {
	file_proto_datarights_proto_rawDescOnce.Do(func() {
		file_proto_datarights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_datarights_proto_rawDesc), len(file_proto_datarights_proto_rawDesc)))
	})
	return file_proto_datarights_proto_rawDescData
}

var file_proto_datarights_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_datarights_proto_goTypes = []any{
	(*GetExportMetricsRequest)(nil),     // 0: datarights.GetExportMetricsRequest
	(*ExportMetricsResponse)(nil),       // 1: datarights.ExportMetricsResponse
	(*reportingpb.ReportWindowSet)(nil), // 2: reporting.ReportWindowSet
	(*reportingpb.CountResult)(nil),     // 3: reporting.CountResult
}
var file_proto_datarights_proto_depIdxs = []int32{
	2, // 0: datarights.GetExportMetricsRequest.window_set:type_name -> reporting.ReportWindowSet
	2, // 1: datarights.ExportMetricsResponse.window_set:type_name -> reporting.ReportWindowSet
	3, // 2: datarights.ExportMetricsResponse.completed_exports:type_name -> reporting.CountResult
	0, // 3: datarights.DatarightsService.GetExportMetrics:input_type -> datarights.GetExportMetricsRequest
	1, // 4: datarights.DatarightsService.GetExportMetrics:output_type -> datarights.ExportMetricsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_datarights_proto_init() }
func file_proto_datarights_proto_init() {
	if File_proto_datarights_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_datarights_proto_rawDesc), len(file_proto_datarights_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_datarights_proto_goTypes,
		DependencyIndexes: file_proto_datarights_proto_depIdxs,
		MessageInfos:      file_proto_datarights_proto_msgTypes,
	}.Build()
	File_proto_datarights_proto = out.File
	file_proto_datarights_proto_goTypes = nil
	file_proto_datarights_proto_depIdxs = nil
}
