// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.0
// source: proto/datarights.proto

package datarightspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatarightsService_GetExportMetrics_FullMethodName = "/datarights.DatarightsService/GetExportMetrics"
)

// DatarightsServiceClient is the client API for DatarightsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatarightsServiceClient interface {
	GetExportMetrics(ctx context.Context, in *GetExportMetricsRequest, opts ...grpc.CallOption) (*ExportMetricsResponse, error)
}

type datarightsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatarightsServiceClient(cc grpc.ClientConnInterface) DatarightsServiceClient {
	return &datarightsServiceClient{cc}
}

func (c *datarightsServiceClient) GetExportMetrics(ctx context.Context, in *GetExportMetricsRequest, opts ...grpc.CallOption) (*ExportMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportMetricsResponse)
	err := c.cc.Invoke(ctx, DatarightsService_GetExportMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatarightsServiceServer is the server API for DatarightsService service.
// All implementations must embed UnimplementedDatarightsServiceServer
// for forward compatibility.
type DatarightsServiceServer interface {
	GetExportMetrics(context.Context, *GetExportMetricsRequest) (*ExportMetricsResponse, error)
	mustEmbedUnimplementedDatarightsServiceServer()
}

// UnimplementedDatarightsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatarightsServiceServer struct{}

func (UnimplementedDatarightsServiceServer) GetExportMetrics(context.Context, *GetExportMetricsRequest) (*ExportMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExportMetrics not implemented")
}
func (UnimplementedDatarightsServiceServer) mustEmbedUnimplementedDatarightsServiceServer() {}
func (UnimplementedDatarightsServiceServer) testEmbeddedByValue()                           {}

// UnsafeDatarightsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatarightsServiceServer will
// result in compilation errors.
type UnsafeDatarightsServiceServer interface {
	mustEmbedUnimplementedDatarightsServiceServer()
}

func RegisterDatarightsServiceServer(s grpc.ServiceRegistrar, srv DatarightsServiceServer) {
	// If the following call panics, it indicates UnimplementedDatarightsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatarightsService_ServiceDesc, srv)
}

func _DatarightsService_GetExportMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExportMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatarightsServiceServer).GetExportMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatarightsService_GetExportMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatarightsServiceServer).GetExportMetrics(ctx, req.(*GetExportMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatarightsService_ServiceDesc is the grpc.ServiceDesc for DatarightsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatarightsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datarights.DatarightsService",
	HandlerType: (*DatarightsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExportMetrics",
			Handler:    _DatarightsService_GetExportMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/datarights.proto",
}
