// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: finance.proto

package financepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultsData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BudgetAmount      int64                  `protobuf:"varint,2,opt,name=budget_amount,json=budgetAmount,proto3" json:"budget_amount,omitempty"`
	EssentialsPercent int32                  `protobuf:"varint,3,opt,name=essentials_percent,json=essentialsPercent,proto3" json:"essentials_percent,omitempty"`
	DesiresPercent    int32                  `protobuf:"varint,4,opt,name=desires_percent,json=desiresPercent,proto3" json:"desires_percent,omitempty"`
	SavingsPercent    int32                  `protobuf:"varint,5,opt,name=savings_percent,json=savingsPercent,proto3" json:"savings_percent,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DefaultsData) Reset() {
	*x = DefaultsData{}
	mi := &file_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultsData) ProtoMessage() {}

func (x *DefaultsData) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultsData.ProtoReflect.Descriptor instead.
func (*DefaultsData) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultsData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DefaultsData) GetBudgetAmount() int64 {
	if x != nil {
		return x.BudgetAmount
	}
	return 0
}

func (x *DefaultsData) GetEssentialsPercent() int32 {
	if x != nil {
		return x.EssentialsPercent
	}
	return 0
}

func (x *DefaultsData) GetDesiresPercent() int32 {
	if x != nil {
		return x.DesiresPercent
	}
	return 0
}

func (x *DefaultsData) GetSavingsPercent() int32 {
	if x != nil {
		return x.SavingsPercent
	}
	return 0
}

func (x *DefaultsData) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetDefaultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultsRequest) Reset() {
	*x = GetDefaultsRequest{}
	mi := &file_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultsRequest) ProtoMessage() {}

func (x *GetDefaultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultsRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultsRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{1}
}

func (x *GetDefaultsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateDefaultsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BudgetAmount      int64                  `protobuf:"varint,2,opt,name=budget_amount,json=budgetAmount,proto3" json:"budget_amount,omitempty"`
	EssentialsPercent int32                  `protobuf:"varint,3,opt,name=essentials_percent,json=essentialsPercent,proto3" json:"essentials_percent,omitempty"`
	DesiresPercent    int32                  `protobuf:"varint,4,opt,name=desires_percent,json=desiresPercent,proto3" json:"desires_percent,omitempty"`
	SavingsPercent    int32                  `protobuf:"varint,5,opt,name=savings_percent,json=savingsPercent,proto3" json:"savings_percent,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateDefaultsRequest) Reset() {
	*x = UpdateDefaultsRequest{}
	mi := &file_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefaultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefaultsRequest) ProtoMessage() {}

func (x *UpdateDefaultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefaultsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDefaultsRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDefaultsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateDefaultsRequest) GetBudgetAmount() int64 {
	if x != nil {
		return x.BudgetAmount
	}
	return 0
}

func (x *UpdateDefaultsRequest) GetEssentialsPercent() int32 {
	if x != nil {
		return x.EssentialsPercent
	}
	return 0
}

func (x *UpdateDefaultsRequest) GetDesiresPercent() int32 {
	if x != nil {
		return x.DesiresPercent
	}
	return 0
}

func (x *UpdateDefaultsRequest) GetSavingsPercent() int32 {
	if x != nil {
		return x.SavingsPercent
	}
	return 0
}

func (x *UpdateDefaultsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CompleteOnboardingRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BudgetAmount      int64                  `protobuf:"varint,2,opt,name=budget_amount,json=budgetAmount,proto3" json:"budget_amount,omitempty"`
	EssentialsPercent int32                  `protobuf:"varint,3,opt,name=essentials_percent,json=essentialsPercent,proto3" json:"essentials_percent,omitempty"`
	DesiresPercent    int32                  `protobuf:"varint,4,opt,name=desires_percent,json=desiresPercent,proto3" json:"desires_percent,omitempty"`
	SavingsPercent    int32                  `protobuf:"varint,5,opt,name=savings_percent,json=savingsPercent,proto3" json:"savings_percent,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompleteOnboardingRequest) Reset() {
	*x = CompleteOnboardingRequest{}
	mi := &file_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingRequest) ProtoMessage() {}

func (x *CompleteOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingRequest.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteOnboardingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetBudgetAmount() int64 {
	if x != nil {
		return x.BudgetAmount
	}
	return 0
}

func (x *CompleteOnboardingRequest) GetEssentialsPercent() int32 {
	if x != nil {
		return x.EssentialsPercent
	}
	return 0
}

func (x *CompleteOnboardingRequest) GetDesiresPercent() int32 {
	if x != nil {
		return x.DesiresPercent
	}
	return 0
}

func (x *CompleteOnboardingRequest) GetSavingsPercent() int32 {
	if x != nil {
		return x.SavingsPercent
	}
	return 0
}

func (x *CompleteOnboardingRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type DefaultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Defaults      *DefaultsData          `protobuf:"bytes,1,opt,name=defaults,proto3" json:"defaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultsResponse) Reset() {
	*x = DefaultsResponse{}
	mi := &file_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultsResponse) ProtoMessage() {}

func (x *DefaultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultsResponse.ProtoReflect.Descriptor instead.
func (*DefaultsResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{4}
}

func (x *DefaultsResponse) GetDefaults() *DefaultsData {
	if x != nil {
		return x.Defaults
	}
	return nil
}

type PeriodData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year              int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Month             int32                  `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
	BudgetAmount      int64                  `protobuf:"varint,5,opt,name=budget_amount,json=budgetAmount,proto3" json:"budget_amount,omitempty"`
	EssentialsPercent int32                  `protobuf:"varint,6,opt,name=essentials_percent,json=essentialsPercent,proto3" json:"essentials_percent,omitempty"`
	DesiresPercent    int32                  `protobuf:"varint,7,opt,name=desires_percent,json=desiresPercent,proto3" json:"desires_percent,omitempty"`
	SavingsPercent    int32                  `protobuf:"varint,8,opt,name=savings_percent,json=savingsPercent,proto3" json:"savings_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeriodData) Reset() {
	*x = PeriodData{}
	mi := &file_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodData) ProtoMessage() {}

func (x *PeriodData) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodData.ProtoReflect.Descriptor instead.
func (*PeriodData) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{5}
}

func (x *PeriodData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeriodData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PeriodData) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *PeriodData) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *PeriodData) GetBudgetAmount() int64 {
	if x != nil {
		return x.BudgetAmount
	}
	return 0
}

func (x *PeriodData) GetEssentialsPercent() int32 {
	if x != nil {
		return x.EssentialsPercent
	}
	return 0
}

func (x *PeriodData) GetDesiresPercent() int32 {
	if x != nil {
		return x.DesiresPercent
	}
	return 0
}

func (x *PeriodData) GetSavingsPercent() int32 {
	if x != nil {
		return x.SavingsPercent
	}
	return 0
}

type GetCurrentPeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPeriodRequest) Reset() {
	*x = GetCurrentPeriodRequest{}
	mi := &file_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPeriodRequest) ProtoMessage() {}

func (x *GetCurrentPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPeriodRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentPeriodRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{6}
}

func (x *GetCurrentPeriodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCurrentPeriodRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetCurrentPeriodRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type CreatePeriodRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year              int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month             int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	BudgetAmount      int64                  `protobuf:"varint,4,opt,name=budget_amount,json=budgetAmount,proto3" json:"budget_amount,omitempty"`
	EssentialsPercent int32                  `protobuf:"varint,5,opt,name=essentials_percent,json=essentialsPercent,proto3" json:"essentials_percent,omitempty"`
	DesiresPercent    int32                  `protobuf:"varint,6,opt,name=desires_percent,json=desiresPercent,proto3" json:"desires_percent,omitempty"`
	SavingsPercent    int32                  `protobuf:"varint,7,opt,name=savings_percent,json=savingsPercent,proto3" json:"savings_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePeriodRequest) Reset() {
	*x = CreatePeriodRequest{}
	mi := &file_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeriodRequest) ProtoMessage() {}

func (x *CreatePeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeriodRequest.ProtoReflect.Descriptor instead.
func (*CreatePeriodRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePeriodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePeriodRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreatePeriodRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *CreatePeriodRequest) GetBudgetAmount() int64 {
	if x != nil {
		return x.BudgetAmount
	}
	return 0
}

func (x *CreatePeriodRequest) GetEssentialsPercent() int32 {
	if x != nil {
		return x.EssentialsPercent
	}
	return 0
}

func (x *CreatePeriodRequest) GetDesiresPercent() int32 {
	if x != nil {
		return x.DesiresPercent
	}
	return 0
}

func (x *CreatePeriodRequest) GetSavingsPercent() int32 {
	if x != nil {
		return x.SavingsPercent
	}
	return 0
}

type UpdatePeriodRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeriodId          string                 `protobuf:"bytes,1,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BudgetAmount      int64                  `protobuf:"varint,3,opt,name=budget_amount,json=budgetAmount,proto3" json:"budget_amount,omitempty"`
	EssentialsPercent int32                  `protobuf:"varint,4,opt,name=essentials_percent,json=essentialsPercent,proto3" json:"essentials_percent,omitempty"`
	DesiresPercent    int32                  `protobuf:"varint,5,opt,name=desires_percent,json=desiresPercent,proto3" json:"desires_percent,omitempty"`
	SavingsPercent    int32                  `protobuf:"varint,6,opt,name=savings_percent,json=savingsPercent,proto3" json:"savings_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdatePeriodRequest) Reset() {
	*x = UpdatePeriodRequest{}
	mi := &file_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePeriodRequest) ProtoMessage() {}

func (x *UpdatePeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePeriodRequest.ProtoReflect.Descriptor instead.
func (*UpdatePeriodRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePeriodRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *UpdatePeriodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePeriodRequest) GetBudgetAmount() int64 {
	if x != nil {
		return x.BudgetAmount
	}
	return 0
}

func (x *UpdatePeriodRequest) GetEssentialsPercent() int32 {
	if x != nil {
		return x.EssentialsPercent
	}
	return 0
}

func (x *UpdatePeriodRequest) GetDesiresPercent() int32 {
	if x != nil {
		return x.DesiresPercent
	}
	return 0
}

func (x *UpdatePeriodRequest) GetSavingsPercent() int32 {
	if x != nil {
		return x.SavingsPercent
	}
	return 0
}

type ListPeriodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeriodsRequest) Reset() {
	*x = ListPeriodsRequest{}
	mi := &file_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeriodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeriodsRequest) ProtoMessage() {}

func (x *ListPeriodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeriodsRequest.ProtoReflect.Descriptor instead.
func (*ListPeriodsRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{9}
}

func (x *ListPeriodsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListPeriodsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPeriodsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PeriodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        *PeriodData            `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodResponse) Reset() {
	*x = PeriodResponse{}
	mi := &file_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodResponse) ProtoMessage() {}

func (x *PeriodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodResponse.ProtoReflect.Descriptor instead.
func (*PeriodResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{10}
}

func (x *PeriodResponse) GetPeriod() *PeriodData {
	if x != nil {
		return x.Period
	}
	return nil
}

type PeriodListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Periods       []*PeriodData          `protobuf:"bytes,1,rep,name=periods,proto3" json:"periods,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodListResponse) Reset() {
	*x = PeriodListResponse{}
	mi := &file_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodListResponse) ProtoMessage() {}

func (x *PeriodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodListResponse.ProtoReflect.Descriptor instead.
func (*PeriodListResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{11}
}

func (x *PeriodListResponse) GetPeriods() []*PeriodData {
	if x != nil {
		return x.Periods
	}
	return nil
}

func (x *PeriodListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TagData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsDefault     bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagData) Reset() {
	*x = TagData{}
	mi := &file_finance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagData) ProtoMessage() {}

func (x *TagData) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagData.ProtoReflect.Descriptor instead.
func (*TagData) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{12}
}

func (x *TagData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TagData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagData) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_finance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{13}
}

func (x *ListTagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_finance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{14}
}

func (x *CreateTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         string                 `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_finance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTagRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *UpdateTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         string                 `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_finance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteTagRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *DeleteTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_finance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{17}
}

type CheckTagUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         string                 `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTagUsageRequest) Reset() {
	*x = CheckTagUsageRequest{}
	mi := &file_finance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTagUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTagUsageRequest) ProtoMessage() {}

func (x *CheckTagUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTagUsageRequest.ProtoReflect.Descriptor instead.
func (*CheckTagUsageRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{18}
}

func (x *CheckTagUsageRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

type TagUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InUse         bool                   `protobuf:"varint,1,opt,name=in_use,json=inUse,proto3" json:"in_use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagUsageResponse) Reset() {
	*x = TagUsageResponse{}
	mi := &file_finance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagUsageResponse) ProtoMessage() {}

func (x *TagUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagUsageResponse.ProtoReflect.Descriptor instead.
func (*TagUsageResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{19}
}

func (x *TagUsageResponse) GetInUse() bool {
	if x != nil {
		return x.InUse
	}
	return false
}

type TagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *TagData               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResponse) Reset() {
	*x = TagResponse{}
	mi := &file_finance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResponse) ProtoMessage() {}

func (x *TagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResponse.ProtoReflect.Descriptor instead.
func (*TagResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{20}
}

func (x *TagResponse) GetTag() *TagData {
	if x != nil {
		return x.Tag
	}
	return nil
}

type TagListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagData             `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListResponse) Reset() {
	*x = TagListResponse{}
	mi := &file_finance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListResponse) ProtoMessage() {}

func (x *TagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListResponse.ProtoReflect.Descriptor instead.
func (*TagListResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{21}
}

func (x *TagListResponse) GetTags() []*TagData {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateProRataExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ExpenseType   string                 `protobuf:"bytes,5,opt,name=expense_type,json=expenseType,proto3" json:"expense_type,omitempty"`
	TagId         string                 `protobuf:"bytes,6,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	ExpenseDate   string                 `protobuf:"bytes,7,opt,name=expense_date,json=expenseDate,proto3" json:"expense_date,omitempty"`
	Months        int32                  `protobuf:"varint,8,opt,name=months,proto3" json:"months,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProRataExpenseRequest) Reset() {
	*x = CreateProRataExpenseRequest{}
	mi := &file_finance_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProRataExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProRataExpenseRequest) ProtoMessage() {}

func (x *CreateProRataExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProRataExpenseRequest.ProtoReflect.Descriptor instead.
func (*CreateProRataExpenseRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{22}
}

func (x *CreateProRataExpenseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProRataExpenseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProRataExpenseRequest) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateProRataExpenseRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateProRataExpenseRequest) GetExpenseType() string {
	if x != nil {
		return x.ExpenseType
	}
	return ""
}

func (x *CreateProRataExpenseRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *CreateProRataExpenseRequest) GetExpenseDate() string {
	if x != nil {
		return x.ExpenseDate
	}
	return ""
}

func (x *CreateProRataExpenseRequest) GetMonths() int32 {
	if x != nil {
		return x.Months
	}
	return 0
}

type ProRataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProRataResponse) Reset() {
	*x = ProRataResponse{}
	mi := &file_finance_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProRataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProRataResponse) ProtoMessage() {}

func (x *ProRataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProRataResponse.ProtoReflect.Descriptor instead.
func (*ProRataResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{23}
}

func (x *ProRataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUpcomingProRataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingProRataRequest) Reset() {
	*x = GetUpcomingProRataRequest{}
	mi := &file_finance_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingProRataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingProRataRequest) ProtoMessage() {}

func (x *GetUpcomingProRataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingProRataRequest.ProtoReflect.Descriptor instead.
func (*GetUpcomingProRataRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{24}
}

func (x *GetUpcomingProRataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpcomingProRataListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcomingProRataListResponse) Reset() {
	*x = UpcomingProRataListResponse{}
	mi := &file_finance_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcomingProRataListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingProRataListResponse) ProtoMessage() {}

func (x *UpcomingProRataListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingProRataListResponse.ProtoReflect.Descriptor instead.
func (*UpcomingProRataListResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{25}
}

func (x *UpcomingProRataListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPeriodSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeriodSummaryRequest) Reset() {
	*x = GetPeriodSummaryRequest{}
	mi := &file_finance_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeriodSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeriodSummaryRequest) ProtoMessage() {}

func (x *GetPeriodSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeriodSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetPeriodSummaryRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{26}
}

func (x *GetPeriodSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPeriodSummaryRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetPeriodSummaryRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type PeriodSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodSummaryResponse) Reset() {
	*x = PeriodSummaryResponse{}
	mi := &file_finance_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodSummaryResponse) ProtoMessage() {}

func (x *PeriodSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodSummaryResponse.ProtoReflect.Descriptor instead.
func (*PeriodSummaryResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{27}
}

func (x *PeriodSummaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSpendingByTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpendingByTagRequest) Reset() {
	*x = GetSpendingByTagRequest{}
	mi := &file_finance_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpendingByTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpendingByTagRequest) ProtoMessage() {}

func (x *GetSpendingByTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpendingByTagRequest.ProtoReflect.Descriptor instead.
func (*GetSpendingByTagRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{28}
}

func (x *GetSpendingByTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSpendingByTagRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetSpendingByTagRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type TagSpendingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagSpendingListResponse) Reset() {
	*x = TagSpendingListResponse{}
	mi := &file_finance_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSpendingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSpendingListResponse) ProtoMessage() {}

func (x *TagSpendingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSpendingListResponse.ProtoReflect.Descriptor instead.
func (*TagSpendingListResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{29}
}

func (x *TagSpendingListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCumulativeSpendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCumulativeSpendRequest) Reset() {
	*x = GetCumulativeSpendRequest{}
	mi := &file_finance_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCumulativeSpendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCumulativeSpendRequest) ProtoMessage() {}

func (x *GetCumulativeSpendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCumulativeSpendRequest.ProtoReflect.Descriptor instead.
func (*GetCumulativeSpendRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{30}
}

func (x *GetCumulativeSpendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCumulativeSpendRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetCumulativeSpendRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type CumulativeSpendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CumulativeSpendResponse) Reset() {
	*x = CumulativeSpendResponse{}
	mi := &file_finance_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CumulativeSpendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CumulativeSpendResponse) ProtoMessage() {}

func (x *CumulativeSpendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CumulativeSpendResponse.ProtoReflect.Descriptor instead.
func (*CumulativeSpendResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{31}
}

func (x *CumulativeSpendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetHistoricalComparisonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoricalComparisonRequest) Reset() {
	*x = GetHistoricalComparisonRequest{}
	mi := &file_finance_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoricalComparisonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoricalComparisonRequest) ProtoMessage() {}

func (x *GetHistoricalComparisonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoricalComparisonRequest.ProtoReflect.Descriptor instead.
func (*GetHistoricalComparisonRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{32}
}

func (x *GetHistoricalComparisonRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetHistoricalComparisonRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetHistoricalComparisonRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type HistoricalComparisonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalComparisonResponse) Reset() {
	*x = HistoricalComparisonResponse{}
	mi := &file_finance_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalComparisonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalComparisonResponse) ProtoMessage() {}

func (x *HistoricalComparisonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalComparisonResponse.ProtoReflect.Descriptor instead.
func (*HistoricalComparisonResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{33}
}

func (x *HistoricalComparisonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_finance_proto protoreflect.FileDescriptor

const file_finance_proto_rawDesc = "" +
	"\n" +
	"\rfinance.proto\x12\afinance\"\xe9\x01\n" +
	"\fDefaultsData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbudget_amount\x18\x02 \x01(\x03R\fbudgetAmount\x12-\n" +
	"\x12essentials_percent\x18\x03 \x01(\x05R\x11essentialsPercent\x12'\n" +
	"\x0fdesires_percent\x18\x04 \x01(\x05R\x0edesiresPercent\x12'\n" +
	"\x0fsavings_percent\x18\x05 \x01(\x05R\x0esavingsPercent\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\"-\n" +
	"\x12GetDefaultsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf2\x01\n" +
	"\x15UpdateDefaultsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbudget_amount\x18\x02 \x01(\x03R\fbudgetAmount\x12-\n" +
	"\x12essentials_percent\x18\x03 \x01(\x05R\x11essentialsPercent\x12'\n" +
	"\x0fdesires_percent\x18\x04 \x01(\x05R\x0edesiresPercent\x12'\n" +
	"\x0fsavings_percent\x18\x05 \x01(\x05R\x0esavingsPercent\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\"\xf6\x01\n" +
	"\x19CompleteOnboardingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbudget_amount\x18\x02 \x01(\x03R\fbudgetAmount\x12-\n" +
	"\x12essentials_percent\x18\x03 \x01(\x05R\x11essentialsPercent\x12'\n" +
	"\x0fdesires_percent\x18\x04 \x01(\x05R\x0edesiresPercent\x12'\n" +
	"\x0fsavings_percent\x18\x05 \x01(\x05R\x0esavingsPercent\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\"E\n" +
	"\x10DefaultsResponse\x121\n" +
	"\bdefaults\x18\x01 \x01(\v2\x15.finance.DefaultsDataR\bdefaults\"\x85\x02\n" +
	"\n" +
	"PeriodData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x04 \x01(\x05R\x05month\x12#\n" +
	"\rbudget_amount\x18\x05 \x01(\x03R\fbudgetAmount\x12-\n" +
	"\x12essentials_percent\x18\x06 \x01(\x05R\x11essentialsPercent\x12'\n" +
	"\x0fdesires_percent\x18\a \x01(\x05R\x0edesiresPercent\x12'\n" +
	"\x0fsavings_percent\x18\b \x01(\x05R\x0esavingsPercent\"\\\n" +
	"\x17GetCurrentPeriodRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"\xfe\x01\n" +
	"\x13CreatePeriodRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\x12#\n" +
	"\rbudget_amount\x18\x04 \x01(\x03R\fbudgetAmount\x12-\n" +
	"\x12essentials_percent\x18\x05 \x01(\x05R\x11essentialsPercent\x12'\n" +
	"\x0fdesires_percent\x18\x06 \x01(\x05R\x0edesiresPercent\x12'\n" +
	"\x0fsavings_percent\x18\a \x01(\x05R\x0esavingsPercent\"\xf1\x01\n" +
	"\x13UpdatePeriodRequest\x12\x1b\n" +
	"\tperiod_id\x18\x01 \x01(\tR\bperiodId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rbudget_amount\x18\x03 \x01(\x03R\fbudgetAmount\x12-\n" +
	"\x12essentials_percent\x18\x04 \x01(\x05R\x11essentialsPercent\x12'\n" +
	"\x0fdesires_percent\x18\x05 \x01(\x05R\x0edesiresPercent\x12'\n" +
	"\x0fsavings_percent\x18\x06 \x01(\x05R\x0esavingsPercent\"^\n" +
	"\x12ListPeriodsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"=\n" +
	"\x0ePeriodResponse\x12+\n" +
	"\x06period\x18\x01 \x01(\v2\x13.finance.PeriodDataR\x06period\"Y\n" +
	"\x12PeriodListResponse\x12-\n" +
	"\aperiods\x18\x01 \x03(\v2\x13.finance.PeriodDataR\aperiods\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"e\n" +
	"\aTagData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\"*\n" +
	"\x0fListTagsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"?\n" +
	"\x10CreateTagRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"V\n" +
	"\x10UpdateTagRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\tR\x05tagId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"B\n" +
	"\x10DeleteTagRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\tR\x05tagId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x13\n" +
	"\x11DeleteTagResponse\"-\n" +
	"\x14CheckTagUsageRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\tR\x05tagId\")\n" +
	"\x10TagUsageResponse\x12\x15\n" +
	"\x06in_use\x18\x01 \x01(\bR\x05inUse\"1\n" +
	"\vTagResponse\x12\"\n" +
	"\x03tag\x18\x01 \x01(\v2\x10.finance.TagDataR\x03tag\"7\n" +
	"\x0fTagListResponse\x12$\n" +
	"\x04tags\x18\x01 \x03(\v2\x10.finance.TagDataR\x04tags\"\xfe\x01\n" +
	"\x1bCreateProRataExpenseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12!\n" +
	"\fexpense_type\x18\x05 \x01(\tR\vexpenseType\x12\x15\n" +
	"\x06tag_id\x18\x06 \x01(\tR\x05tagId\x12!\n" +
	"\fexpense_date\x18\a \x01(\tR\vexpenseDate\x12\x16\n" +
	"\x06months\x18\b \x01(\x05R\x06months\"+\n" +
	"\x0fProRataResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\x19GetUpcomingProRataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\x1bUpcomingProRataListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\\\n" +
	"\x17GetPeriodSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"1\n" +
	"\x15PeriodSummaryResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\\\n" +
	"\x17GetSpendingByTagRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"3\n" +
	"\x17TagSpendingListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"^\n" +
	"\x19GetCumulativeSpendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"3\n" +
	"\x17CumulativeSpendResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"c\n" +
	"\x1eGetHistoricalComparisonRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"8\n" +
	"\x1cHistoricalComparisonResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x97\v\n" +
	"\x0eFinanceService\x12E\n" +
	"\vGetDefaults\x12\x1b.finance.GetDefaultsRequest\x1a\x19.finance.DefaultsResponse\x12K\n" +
	"\x0eUpdateDefaults\x12\x1e.finance.UpdateDefaultsRequest\x1a\x19.finance.DefaultsResponse\x12S\n" +
	"\x12CompleteOnboarding\x12\".finance.CompleteOnboardingRequest\x1a\x19.finance.DefaultsResponse\x12M\n" +
	"\x10GetCurrentPeriod\x12 .finance.GetCurrentPeriodRequest\x1a\x17.finance.PeriodResponse\x12E\n" +
	"\fCreatePeriod\x12\x1c.finance.CreatePeriodRequest\x1a\x17.finance.PeriodResponse\x12E\n" +
	"\fUpdatePeriod\x12\x1c.finance.UpdatePeriodRequest\x1a\x17.finance.PeriodResponse\x12G\n" +
	"\vListPeriods\x12\x1b.finance.ListPeriodsRequest\x1a\x1b.finance.PeriodListResponse\x12>\n" +
	"\bListTags\x12\x18.finance.ListTagsRequest\x1a\x18.finance.TagListResponse\x12<\n" +
	"\tCreateTag\x12\x19.finance.CreateTagRequest\x1a\x14.finance.TagResponse\x12<\n" +
	"\tUpdateTag\x12\x19.finance.UpdateTagRequest\x1a\x14.finance.TagResponse\x12B\n" +
	"\tDeleteTag\x12\x19.finance.DeleteTagRequest\x1a\x1a.finance.DeleteTagResponse\x12I\n" +
	"\rCheckTagUsage\x12\x1d.finance.CheckTagUsageRequest\x1a\x19.finance.TagUsageResponse\x12V\n" +
	"\x14CreateProRataExpense\x12$.finance.CreateProRataExpenseRequest\x1a\x18.finance.ProRataResponse\x12^\n" +
	"\x12GetUpcomingProRata\x12\".finance.GetUpcomingProRataRequest\x1a$.finance.UpcomingProRataListResponse\x12T\n" +
	"\x10GetPeriodSummary\x12 .finance.GetPeriodSummaryRequest\x1a\x1e.finance.PeriodSummaryResponse\x12V\n" +
	"\x10GetSpendingByTag\x12 .finance.GetSpendingByTagRequest\x1a .finance.TagSpendingListResponse\x12Z\n" +
	"\x12GetCumulativeSpend\x12\".finance.GetCumulativeSpendRequest\x1a .finance.CumulativeSpendResponse\x12i\n" +
	"\x17GetHistoricalComparison\x12'.finance.GetHistoricalComparisonRequest\x1a%.finance.HistoricalComparisonResponseB?Z=github.com/ItsThompson/gofin/services/finance/proto/financepbb\x06proto3"

var (
	file_finance_proto_rawDescOnce sync.Once
	file_finance_proto_rawDescData []byte
)

func file_finance_proto_rawDescGZIP() []byte {
	file_finance_proto_rawDescOnce.Do(func() {
		file_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)))
	})
	return file_finance_proto_rawDescData
}

var file_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_finance_proto_goTypes = []any{
	(*DefaultsData)(nil),                   // 0: finance.DefaultsData
	(*GetDefaultsRequest)(nil),             // 1: finance.GetDefaultsRequest
	(*UpdateDefaultsRequest)(nil),          // 2: finance.UpdateDefaultsRequest
	(*CompleteOnboardingRequest)(nil),      // 3: finance.CompleteOnboardingRequest
	(*DefaultsResponse)(nil),               // 4: finance.DefaultsResponse
	(*PeriodData)(nil),                     // 5: finance.PeriodData
	(*GetCurrentPeriodRequest)(nil),        // 6: finance.GetCurrentPeriodRequest
	(*CreatePeriodRequest)(nil),            // 7: finance.CreatePeriodRequest
	(*UpdatePeriodRequest)(nil),            // 8: finance.UpdatePeriodRequest
	(*ListPeriodsRequest)(nil),             // 9: finance.ListPeriodsRequest
	(*PeriodResponse)(nil),                 // 10: finance.PeriodResponse
	(*PeriodListResponse)(nil),             // 11: finance.PeriodListResponse
	(*TagData)(nil),                        // 12: finance.TagData
	(*ListTagsRequest)(nil),                // 13: finance.ListTagsRequest
	(*CreateTagRequest)(nil),               // 14: finance.CreateTagRequest
	(*UpdateTagRequest)(nil),               // 15: finance.UpdateTagRequest
	(*DeleteTagRequest)(nil),               // 16: finance.DeleteTagRequest
	(*DeleteTagResponse)(nil),              // 17: finance.DeleteTagResponse
	(*CheckTagUsageRequest)(nil),           // 18: finance.CheckTagUsageRequest
	(*TagUsageResponse)(nil),               // 19: finance.TagUsageResponse
	(*TagResponse)(nil),                    // 20: finance.TagResponse
	(*TagListResponse)(nil),                // 21: finance.TagListResponse
	(*CreateProRataExpenseRequest)(nil),    // 22: finance.CreateProRataExpenseRequest
	(*ProRataResponse)(nil),                // 23: finance.ProRataResponse
	(*GetUpcomingProRataRequest)(nil),      // 24: finance.GetUpcomingProRataRequest
	(*UpcomingProRataListResponse)(nil),    // 25: finance.UpcomingProRataListResponse
	(*GetPeriodSummaryRequest)(nil),        // 26: finance.GetPeriodSummaryRequest
	(*PeriodSummaryResponse)(nil),          // 27: finance.PeriodSummaryResponse
	(*GetSpendingByTagRequest)(nil),        // 28: finance.GetSpendingByTagRequest
	(*TagSpendingListResponse)(nil),        // 29: finance.TagSpendingListResponse
	(*GetCumulativeSpendRequest)(nil),      // 30: finance.GetCumulativeSpendRequest
	(*CumulativeSpendResponse)(nil),        // 31: finance.CumulativeSpendResponse
	(*GetHistoricalComparisonRequest)(nil), // 32: finance.GetHistoricalComparisonRequest
	(*HistoricalComparisonResponse)(nil),   // 33: finance.HistoricalComparisonResponse
}
var file_finance_proto_depIdxs = []int32{
	0,  // 0: finance.DefaultsResponse.defaults:type_name -> finance.DefaultsData
	5,  // 1: finance.PeriodResponse.period:type_name -> finance.PeriodData
	5,  // 2: finance.PeriodListResponse.periods:type_name -> finance.PeriodData
	12, // 3: finance.TagResponse.tag:type_name -> finance.TagData
	12, // 4: finance.TagListResponse.tags:type_name -> finance.TagData
	1,  // 5: finance.FinanceService.GetDefaults:input_type -> finance.GetDefaultsRequest
	2,  // 6: finance.FinanceService.UpdateDefaults:input_type -> finance.UpdateDefaultsRequest
	3,  // 7: finance.FinanceService.CompleteOnboarding:input_type -> finance.CompleteOnboardingRequest
	6,  // 8: finance.FinanceService.GetCurrentPeriod:input_type -> finance.GetCurrentPeriodRequest
	7,  // 9: finance.FinanceService.CreatePeriod:input_type -> finance.CreatePeriodRequest
	8,  // 10: finance.FinanceService.UpdatePeriod:input_type -> finance.UpdatePeriodRequest
	9,  // 11: finance.FinanceService.ListPeriods:input_type -> finance.ListPeriodsRequest
	13, // 12: finance.FinanceService.ListTags:input_type -> finance.ListTagsRequest
	14, // 13: finance.FinanceService.CreateTag:input_type -> finance.CreateTagRequest
	15, // 14: finance.FinanceService.UpdateTag:input_type -> finance.UpdateTagRequest
	16, // 15: finance.FinanceService.DeleteTag:input_type -> finance.DeleteTagRequest
	18, // 16: finance.FinanceService.CheckTagUsage:input_type -> finance.CheckTagUsageRequest
	22, // 17: finance.FinanceService.CreateProRataExpense:input_type -> finance.CreateProRataExpenseRequest
	24, // 18: finance.FinanceService.GetUpcomingProRata:input_type -> finance.GetUpcomingProRataRequest
	26, // 19: finance.FinanceService.GetPeriodSummary:input_type -> finance.GetPeriodSummaryRequest
	28, // 20: finance.FinanceService.GetSpendingByTag:input_type -> finance.GetSpendingByTagRequest
	30, // 21: finance.FinanceService.GetCumulativeSpend:input_type -> finance.GetCumulativeSpendRequest
	32, // 22: finance.FinanceService.GetHistoricalComparison:input_type -> finance.GetHistoricalComparisonRequest
	4,  // 23: finance.FinanceService.GetDefaults:output_type -> finance.DefaultsResponse
	4,  // 24: finance.FinanceService.UpdateDefaults:output_type -> finance.DefaultsResponse
	4,  // 25: finance.FinanceService.CompleteOnboarding:output_type -> finance.DefaultsResponse
	10, // 26: finance.FinanceService.GetCurrentPeriod:output_type -> finance.PeriodResponse
	10, // 27: finance.FinanceService.CreatePeriod:output_type -> finance.PeriodResponse
	10, // 28: finance.FinanceService.UpdatePeriod:output_type -> finance.PeriodResponse
	11, // 29: finance.FinanceService.ListPeriods:output_type -> finance.PeriodListResponse
	21, // 30: finance.FinanceService.ListTags:output_type -> finance.TagListResponse
	20, // 31: finance.FinanceService.CreateTag:output_type -> finance.TagResponse
	20, // 32: finance.FinanceService.UpdateTag:output_type -> finance.TagResponse
	17, // 33: finance.FinanceService.DeleteTag:output_type -> finance.DeleteTagResponse
	19, // 34: finance.FinanceService.CheckTagUsage:output_type -> finance.TagUsageResponse
	23, // 35: finance.FinanceService.CreateProRataExpense:output_type -> finance.ProRataResponse
	25, // 36: finance.FinanceService.GetUpcomingProRata:output_type -> finance.UpcomingProRataListResponse
	27, // 37: finance.FinanceService.GetPeriodSummary:output_type -> finance.PeriodSummaryResponse
	29, // 38: finance.FinanceService.GetSpendingByTag:output_type -> finance.TagSpendingListResponse
	31, // 39: finance.FinanceService.GetCumulativeSpend:output_type -> finance.CumulativeSpendResponse
	33, // 40: finance.FinanceService.GetHistoricalComparison:output_type -> finance.HistoricalComparisonResponse
	23, // [23:41] is the sub-list for method output_type
	5,  // [5:23] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_finance_proto_init() }
func file_finance_proto_init() {
	if File_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_proto_goTypes,
		DependencyIndexes: file_finance_proto_depIdxs,
		MessageInfos:      file_finance_proto_msgTypes,
	}.Build()
	File_finance_proto = out.File
	file_finance_proto_goTypes = nil
	file_finance_proto_depIdxs = nil
}
