// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: finance.proto

package financepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FinanceService_GetDefaults_FullMethodName             = "/finance.FinanceService/GetDefaults"
	FinanceService_UpdateDefaults_FullMethodName          = "/finance.FinanceService/UpdateDefaults"
	FinanceService_CompleteOnboarding_FullMethodName      = "/finance.FinanceService/CompleteOnboarding"
	FinanceService_GetCurrentPeriod_FullMethodName        = "/finance.FinanceService/GetCurrentPeriod"
	FinanceService_CreatePeriod_FullMethodName            = "/finance.FinanceService/CreatePeriod"
	FinanceService_UpdatePeriod_FullMethodName            = "/finance.FinanceService/UpdatePeriod"
	FinanceService_ListPeriods_FullMethodName             = "/finance.FinanceService/ListPeriods"
	FinanceService_ListTags_FullMethodName                = "/finance.FinanceService/ListTags"
	FinanceService_CreateTag_FullMethodName               = "/finance.FinanceService/CreateTag"
	FinanceService_UpdateTag_FullMethodName               = "/finance.FinanceService/UpdateTag"
	FinanceService_DeleteTag_FullMethodName               = "/finance.FinanceService/DeleteTag"
	FinanceService_CheckTagUsage_FullMethodName           = "/finance.FinanceService/CheckTagUsage"
	FinanceService_CreateProRataExpense_FullMethodName    = "/finance.FinanceService/CreateProRataExpense"
	FinanceService_GetUpcomingProRata_FullMethodName      = "/finance.FinanceService/GetUpcomingProRata"
	FinanceService_GetPeriodSummary_FullMethodName        = "/finance.FinanceService/GetPeriodSummary"
	FinanceService_GetSpendingByTag_FullMethodName        = "/finance.FinanceService/GetSpendingByTag"
	FinanceService_GetCumulativeSpend_FullMethodName      = "/finance.FinanceService/GetCumulativeSpend"
	FinanceService_GetHistoricalComparison_FullMethodName = "/finance.FinanceService/GetHistoricalComparison"
)

// FinanceServiceClient is the client API for FinanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinanceServiceClient interface {
	// Default settings
	GetDefaults(ctx context.Context, in *GetDefaultsRequest, opts ...grpc.CallOption) (*DefaultsResponse, error)
	UpdateDefaults(ctx context.Context, in *UpdateDefaultsRequest, opts ...grpc.CallOption) (*DefaultsResponse, error)
	CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...grpc.CallOption) (*DefaultsResponse, error)
	// Budget period operations (stubs for later tickets)
	GetCurrentPeriod(ctx context.Context, in *GetCurrentPeriodRequest, opts ...grpc.CallOption) (*PeriodResponse, error)
	CreatePeriod(ctx context.Context, in *CreatePeriodRequest, opts ...grpc.CallOption) (*PeriodResponse, error)
	UpdatePeriod(ctx context.Context, in *UpdatePeriodRequest, opts ...grpc.CallOption) (*PeriodResponse, error)
	ListPeriods(ctx context.Context, in *ListPeriodsRequest, opts ...grpc.CallOption) (*PeriodListResponse, error)
	// Tag operations (stubs for later tickets)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*TagListResponse, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagResponse, error)
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*TagResponse, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	CheckTagUsage(ctx context.Context, in *CheckTagUsageRequest, opts ...grpc.CallOption) (*TagUsageResponse, error)
	// Pro-rata (stubs for later tickets)
	CreateProRataExpense(ctx context.Context, in *CreateProRataExpenseRequest, opts ...grpc.CallOption) (*ProRataResponse, error)
	GetUpcomingProRata(ctx context.Context, in *GetUpcomingProRataRequest, opts ...grpc.CallOption) (*UpcomingProRataListResponse, error)
	// Dashboard aggregation (stubs for later tickets)
	GetPeriodSummary(ctx context.Context, in *GetPeriodSummaryRequest, opts ...grpc.CallOption) (*PeriodSummaryResponse, error)
	GetSpendingByTag(ctx context.Context, in *GetSpendingByTagRequest, opts ...grpc.CallOption) (*TagSpendingListResponse, error)
	GetCumulativeSpend(ctx context.Context, in *GetCumulativeSpendRequest, opts ...grpc.CallOption) (*CumulativeSpendResponse, error)
	GetHistoricalComparison(ctx context.Context, in *GetHistoricalComparisonRequest, opts ...grpc.CallOption) (*HistoricalComparisonResponse, error)
}

type financeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanceServiceClient(cc grpc.ClientConnInterface) FinanceServiceClient {
	return &financeServiceClient{cc}
}

func (c *financeServiceClient) GetDefaults(ctx context.Context, in *GetDefaultsRequest, opts ...grpc.CallOption) (*DefaultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefaultsResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetDefaults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) UpdateDefaults(ctx context.Context, in *UpdateDefaultsRequest, opts ...grpc.CallOption) (*DefaultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefaultsResponse)
	err := c.cc.Invoke(ctx, FinanceService_UpdateDefaults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...grpc.CallOption) (*DefaultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefaultsResponse)
	err := c.cc.Invoke(ctx, FinanceService_CompleteOnboarding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetCurrentPeriod(ctx context.Context, in *GetCurrentPeriodRequest, opts ...grpc.CallOption) (*PeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeriodResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetCurrentPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) CreatePeriod(ctx context.Context, in *CreatePeriodRequest, opts ...grpc.CallOption) (*PeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeriodResponse)
	err := c.cc.Invoke(ctx, FinanceService_CreatePeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) UpdatePeriod(ctx context.Context, in *UpdatePeriodRequest, opts ...grpc.CallOption) (*PeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeriodResponse)
	err := c.cc.Invoke(ctx, FinanceService_UpdatePeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) ListPeriods(ctx context.Context, in *ListPeriodsRequest, opts ...grpc.CallOption) (*PeriodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeriodListResponse)
	err := c.cc.Invoke(ctx, FinanceService_ListPeriods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*TagListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagListResponse)
	err := c.cc.Invoke(ctx, FinanceService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, FinanceService_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, FinanceService_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, FinanceService_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) CheckTagUsage(ctx context.Context, in *CheckTagUsageRequest, opts ...grpc.CallOption) (*TagUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagUsageResponse)
	err := c.cc.Invoke(ctx, FinanceService_CheckTagUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) CreateProRataExpense(ctx context.Context, in *CreateProRataExpenseRequest, opts ...grpc.CallOption) (*ProRataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProRataResponse)
	err := c.cc.Invoke(ctx, FinanceService_CreateProRataExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetUpcomingProRata(ctx context.Context, in *GetUpcomingProRataRequest, opts ...grpc.CallOption) (*UpcomingProRataListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpcomingProRataListResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetUpcomingProRata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetPeriodSummary(ctx context.Context, in *GetPeriodSummaryRequest, opts ...grpc.CallOption) (*PeriodSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeriodSummaryResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetPeriodSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetSpendingByTag(ctx context.Context, in *GetSpendingByTagRequest, opts ...grpc.CallOption) (*TagSpendingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagSpendingListResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetSpendingByTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetCumulativeSpend(ctx context.Context, in *GetCumulativeSpendRequest, opts ...grpc.CallOption) (*CumulativeSpendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CumulativeSpendResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetCumulativeSpend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetHistoricalComparison(ctx context.Context, in *GetHistoricalComparisonRequest, opts ...grpc.CallOption) (*HistoricalComparisonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoricalComparisonResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetHistoricalComparison_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceServiceServer is the server API for FinanceService service.
// All implementations must embed UnimplementedFinanceServiceServer
// for forward compatibility.
type FinanceServiceServer interface {
	// Default settings
	GetDefaults(context.Context, *GetDefaultsRequest) (*DefaultsResponse, error)
	UpdateDefaults(context.Context, *UpdateDefaultsRequest) (*DefaultsResponse, error)
	CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*DefaultsResponse, error)
	// Budget period operations (stubs for later tickets)
	GetCurrentPeriod(context.Context, *GetCurrentPeriodRequest) (*PeriodResponse, error)
	CreatePeriod(context.Context, *CreatePeriodRequest) (*PeriodResponse, error)
	UpdatePeriod(context.Context, *UpdatePeriodRequest) (*PeriodResponse, error)
	ListPeriods(context.Context, *ListPeriodsRequest) (*PeriodListResponse, error)
	// Tag operations (stubs for later tickets)
	ListTags(context.Context, *ListTagsRequest) (*TagListResponse, error)
	CreateTag(context.Context, *CreateTagRequest) (*TagResponse, error)
	UpdateTag(context.Context, *UpdateTagRequest) (*TagResponse, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	CheckTagUsage(context.Context, *CheckTagUsageRequest) (*TagUsageResponse, error)
	// Pro-rata (stubs for later tickets)
	CreateProRataExpense(context.Context, *CreateProRataExpenseRequest) (*ProRataResponse, error)
	GetUpcomingProRata(context.Context, *GetUpcomingProRataRequest) (*UpcomingProRataListResponse, error)
	// Dashboard aggregation (stubs for later tickets)
	GetPeriodSummary(context.Context, *GetPeriodSummaryRequest) (*PeriodSummaryResponse, error)
	GetSpendingByTag(context.Context, *GetSpendingByTagRequest) (*TagSpendingListResponse, error)
	GetCumulativeSpend(context.Context, *GetCumulativeSpendRequest) (*CumulativeSpendResponse, error)
	GetHistoricalComparison(context.Context, *GetHistoricalComparisonRequest) (*HistoricalComparisonResponse, error)
	mustEmbedUnimplementedFinanceServiceServer()
}

// UnimplementedFinanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinanceServiceServer struct{}

func (UnimplementedFinanceServiceServer) GetDefaults(context.Context, *GetDefaultsRequest) (*DefaultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefaults not implemented")
}
func (UnimplementedFinanceServiceServer) UpdateDefaults(context.Context, *UpdateDefaultsRequest) (*DefaultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDefaults not implemented")
}
func (UnimplementedFinanceServiceServer) CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*DefaultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteOnboarding not implemented")
}
func (UnimplementedFinanceServiceServer) GetCurrentPeriod(context.Context, *GetCurrentPeriodRequest) (*PeriodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentPeriod not implemented")
}
func (UnimplementedFinanceServiceServer) CreatePeriod(context.Context, *CreatePeriodRequest) (*PeriodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePeriod not implemented")
}
func (UnimplementedFinanceServiceServer) UpdatePeriod(context.Context, *UpdatePeriodRequest) (*PeriodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePeriod not implemented")
}
func (UnimplementedFinanceServiceServer) ListPeriods(context.Context, *ListPeriodsRequest) (*PeriodListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeriods not implemented")
}
func (UnimplementedFinanceServiceServer) ListTags(context.Context, *ListTagsRequest) (*TagListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedFinanceServiceServer) CreateTag(context.Context, *CreateTagRequest) (*TagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedFinanceServiceServer) UpdateTag(context.Context, *UpdateTagRequest) (*TagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedFinanceServiceServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedFinanceServiceServer) CheckTagUsage(context.Context, *CheckTagUsageRequest) (*TagUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTagUsage not implemented")
}
func (UnimplementedFinanceServiceServer) CreateProRataExpense(context.Context, *CreateProRataExpenseRequest) (*ProRataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProRataExpense not implemented")
}
func (UnimplementedFinanceServiceServer) GetUpcomingProRata(context.Context, *GetUpcomingProRataRequest) (*UpcomingProRataListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUpcomingProRata not implemented")
}
func (UnimplementedFinanceServiceServer) GetPeriodSummary(context.Context, *GetPeriodSummaryRequest) (*PeriodSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeriodSummary not implemented")
}
func (UnimplementedFinanceServiceServer) GetSpendingByTag(context.Context, *GetSpendingByTagRequest) (*TagSpendingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpendingByTag not implemented")
}
func (UnimplementedFinanceServiceServer) GetCumulativeSpend(context.Context, *GetCumulativeSpendRequest) (*CumulativeSpendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCumulativeSpend not implemented")
}
func (UnimplementedFinanceServiceServer) GetHistoricalComparison(context.Context, *GetHistoricalComparisonRequest) (*HistoricalComparisonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoricalComparison not implemented")
}
func (UnimplementedFinanceServiceServer) mustEmbedUnimplementedFinanceServiceServer() {}
func (UnimplementedFinanceServiceServer) testEmbeddedByValue()                        {}

// UnsafeFinanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinanceServiceServer will
// result in compilation errors.
type UnsafeFinanceServiceServer interface {
	mustEmbedUnimplementedFinanceServiceServer()
}

func RegisterFinanceServiceServer(s grpc.ServiceRegistrar, srv FinanceServiceServer) {
	// If the following call panics, it indicates UnimplementedFinanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FinanceService_ServiceDesc, srv)
}

func _FinanceService_GetDefaults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetDefaults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetDefaults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetDefaults(ctx, req.(*GetDefaultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_UpdateDefaults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDefaultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).UpdateDefaults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_UpdateDefaults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).UpdateDefaults(ctx, req.(*UpdateDefaultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_CompleteOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).CompleteOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_CompleteOnboarding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).CompleteOnboarding(ctx, req.(*CompleteOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetCurrentPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetCurrentPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetCurrentPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetCurrentPeriod(ctx, req.(*GetCurrentPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_CreatePeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).CreatePeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_CreatePeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).CreatePeriod(ctx, req.(*CreatePeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_UpdatePeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).UpdatePeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_UpdatePeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).UpdatePeriod(ctx, req.(*UpdatePeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_ListPeriods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeriodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).ListPeriods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_ListPeriods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).ListPeriods(ctx, req.(*ListPeriodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_CheckTagUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTagUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).CheckTagUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_CheckTagUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).CheckTagUsage(ctx, req.(*CheckTagUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_CreateProRataExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProRataExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).CreateProRataExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_CreateProRataExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).CreateProRataExpense(ctx, req.(*CreateProRataExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetUpcomingProRata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpcomingProRataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetUpcomingProRata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetUpcomingProRata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetUpcomingProRata(ctx, req.(*GetUpcomingProRataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetPeriodSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeriodSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetPeriodSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetPeriodSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetPeriodSummary(ctx, req.(*GetPeriodSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetSpendingByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpendingByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetSpendingByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetSpendingByTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetSpendingByTag(ctx, req.(*GetSpendingByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetCumulativeSpend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCumulativeSpendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetCumulativeSpend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetCumulativeSpend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetCumulativeSpend(ctx, req.(*GetCumulativeSpendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetHistoricalComparison_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoricalComparisonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetHistoricalComparison(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetHistoricalComparison_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetHistoricalComparison(ctx, req.(*GetHistoricalComparisonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinanceService_ServiceDesc is the grpc.ServiceDesc for FinanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finance.FinanceService",
	HandlerType: (*FinanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDefaults",
			Handler:    _FinanceService_GetDefaults_Handler,
		},
		{
			MethodName: "UpdateDefaults",
			Handler:    _FinanceService_UpdateDefaults_Handler,
		},
		{
			MethodName: "CompleteOnboarding",
			Handler:    _FinanceService_CompleteOnboarding_Handler,
		},
		{
			MethodName: "GetCurrentPeriod",
			Handler:    _FinanceService_GetCurrentPeriod_Handler,
		},
		{
			MethodName: "CreatePeriod",
			Handler:    _FinanceService_CreatePeriod_Handler,
		},
		{
			MethodName: "UpdatePeriod",
			Handler:    _FinanceService_UpdatePeriod_Handler,
		},
		{
			MethodName: "ListPeriods",
			Handler:    _FinanceService_ListPeriods_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _FinanceService_ListTags_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _FinanceService_CreateTag_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _FinanceService_UpdateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _FinanceService_DeleteTag_Handler,
		},
		{
			MethodName: "CheckTagUsage",
			Handler:    _FinanceService_CheckTagUsage_Handler,
		},
		{
			MethodName: "CreateProRataExpense",
			Handler:    _FinanceService_CreateProRataExpense_Handler,
		},
		{
			MethodName: "GetUpcomingProRata",
			Handler:    _FinanceService_GetUpcomingProRata_Handler,
		},
		{
			MethodName: "GetPeriodSummary",
			Handler:    _FinanceService_GetPeriodSummary_Handler,
		},
		{
			MethodName: "GetSpendingByTag",
			Handler:    _FinanceService_GetSpendingByTag_Handler,
		},
		{
			MethodName: "GetCumulativeSpend",
			Handler:    _FinanceService_GetCumulativeSpend_Handler,
		},
		{
			MethodName: "GetHistoricalComparison",
			Handler:    _FinanceService_GetHistoricalComparison_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finance.proto",
}
