// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blacklistToken = `-- name: BlacklistToken :exec
INSERT INTO auth.refresh_token_blacklist (jti, user_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (jti) DO NOTHING
`

type BlacklistTokenParams struct {
	Jti       string             `json:"jti"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) BlacklistToken(ctx context.Context, arg BlacklistTokenParams) error {
	_, err := q.db.Exec(ctx, blacklistToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	return err
}

const cleanupExpiredBlacklist = `-- name: CleanupExpiredBlacklist :exec
DELETE FROM auth.refresh_token_blacklist WHERE expires_at < now()
`

func (q *Queries) CleanupExpiredBlacklist(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredBlacklist)
	return err
}

const completeOnboarding = `-- name: CompleteOnboarding :one
UPDATE auth.users
SET has_completed_onboarding = true,
    onboarding_completed_at = COALESCE(onboarding_completed_at, now()),
    currency = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, username, email, password_hash, role, currency, has_completed_onboarding, tokens_revoked_at, created_at, updated_at, onboarding_completed_at
`

type CompleteOnboardingParams struct {
	Currency string      `json:"currency"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) CompleteOnboarding(ctx context.Context, arg CompleteOnboardingParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, completeOnboarding, arg.Currency, arg.ID)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Currency,
		&i.HasCompletedOnboarding,
		&i.TokensRevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingCompletedAt,
	)
	return i, err
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
INSERT INTO auth.refresh_token_blacklist (jti, user_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (jti) DO NOTHING
RETURNING jti
`

type ConsumeRefreshTokenParams struct {
	Jti       string             `json:"jti"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ConsumeRefreshToken(ctx context.Context, arg ConsumeRefreshTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	var jti string
	err := row.Scan(&jti)
	return jti, err
}

const countOnboardingCompletionsInWindows = `-- name: CountOnboardingCompletionsInWindows :one
SELECT
    count(*) FILTER (WHERE onboarding_completed_at >= $1 AND onboarding_completed_at < $2) AS report_week,
    count(*) FILTER (WHERE onboarding_completed_at >= $3 AND onboarding_completed_at < $4) AS previous_week,
    count(*) FILTER (WHERE onboarding_completed_at >= $5 AND onboarding_completed_at < $6) AS trailing_four_weeks_total
FROM auth.users
WHERE onboarding_completed_at >= $5 AND onboarding_completed_at < $2
`

type CountOnboardingCompletionsInWindowsParams struct {
	OnboardingCompletedAt   pgtype.Timestamptz `json:"onboarding_completed_at"`
	OnboardingCompletedAt_2 pgtype.Timestamptz `json:"onboarding_completed_at_2"`
	OnboardingCompletedAt_3 pgtype.Timestamptz `json:"onboarding_completed_at_3"`
	OnboardingCompletedAt_4 pgtype.Timestamptz `json:"onboarding_completed_at_4"`
	OnboardingCompletedAt_5 pgtype.Timestamptz `json:"onboarding_completed_at_5"`
	OnboardingCompletedAt_6 pgtype.Timestamptz `json:"onboarding_completed_at_6"`
}

type CountOnboardingCompletionsInWindowsRow struct {
	ReportWeek             int64 `json:"report_week"`
	PreviousWeek           int64 `json:"previous_week"`
	TrailingFourWeeksTotal int64 `json:"trailing_four_weeks_total"`
}

func (q *Queries) CountOnboardingCompletionsInWindows(ctx context.Context, arg CountOnboardingCompletionsInWindowsParams) (CountOnboardingCompletionsInWindowsRow, error) {
	row := q.db.QueryRow(ctx, countOnboardingCompletionsInWindows,
		arg.OnboardingCompletedAt,
		arg.OnboardingCompletedAt_2,
		arg.OnboardingCompletedAt_3,
		arg.OnboardingCompletedAt_4,
		arg.OnboardingCompletedAt_5,
		arg.OnboardingCompletedAt_6,
	)
	var i CountOnboardingCompletionsInWindowsRow
	err := row.Scan(&i.ReportWeek, &i.PreviousWeek, &i.TrailingFourWeeksTotal)
	return i, err
}

const countUsersCreatedInWindows = `-- name: CountUsersCreatedInWindows :one
SELECT
    count(*) FILTER (WHERE created_at >= $1 AND created_at < $2) AS report_week,
    count(*) FILTER (WHERE created_at >= $3 AND created_at < $4) AS previous_week,
    count(*) FILTER (WHERE created_at >= $5 AND created_at < $6) AS trailing_four_weeks_total
FROM auth.users
WHERE created_at >= $5 AND created_at < $2
`

type CountUsersCreatedInWindowsParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	CreatedAt_3 pgtype.Timestamptz `json:"created_at_3"`
	CreatedAt_4 pgtype.Timestamptz `json:"created_at_4"`
	CreatedAt_5 pgtype.Timestamptz `json:"created_at_5"`
	CreatedAt_6 pgtype.Timestamptz `json:"created_at_6"`
}

type CountUsersCreatedInWindowsRow struct {
	ReportWeek             int64 `json:"report_week"`
	PreviousWeek           int64 `json:"previous_week"`
	TrailingFourWeeksTotal int64 `json:"trailing_four_weeks_total"`
}

func (q *Queries) CountUsersCreatedInWindows(ctx context.Context, arg CountUsersCreatedInWindowsParams) (CountUsersCreatedInWindowsRow, error) {
	row := q.db.QueryRow(ctx, countUsersCreatedInWindows,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.CreatedAt_3,
		arg.CreatedAt_4,
		arg.CreatedAt_5,
		arg.CreatedAt_6,
	)
	var i CountUsersCreatedInWindowsRow
	err := row.Scan(&i.ReportWeek, &i.PreviousWeek, &i.TrailingFourWeeksTotal)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (username, email, password_hash, role, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, password_hash, role, currency, has_completed_onboarding, tokens_revoked_at, created_at, updated_at, onboarding_completed_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Currency     string `json:"currency"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Currency,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Currency,
		&i.HasCompletedOnboarding,
		&i.TokensRevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingCompletedAt,
	)
	return i, err
}

const deleteRefreshTokenBlacklist = `-- name: DeleteRefreshTokenBlacklist :exec
DELETE FROM auth.refresh_token_blacklist WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokenBlacklist(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenBlacklist, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM auth.users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getTokensRevokedAt = `-- name: GetTokensRevokedAt :one
SELECT tokens_revoked_at FROM auth.users WHERE id = $1
`

func (q *Queries) GetTokensRevokedAt(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getTokensRevokedAt, id)
	var tokens_revoked_at pgtype.Timestamptz
	err := row.Scan(&tokens_revoked_at)
	return tokens_revoked_at, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, role, currency, has_completed_onboarding, tokens_revoked_at, created_at, updated_at, onboarding_completed_at FROM auth.users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Currency,
		&i.HasCompletedOnboarding,
		&i.TokensRevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingCompletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, role, currency, has_completed_onboarding, tokens_revoked_at, created_at, updated_at, onboarding_completed_at FROM auth.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Currency,
		&i.HasCompletedOnboarding,
		&i.TokensRevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingCompletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, role, currency, has_completed_onboarding, tokens_revoked_at, created_at, updated_at, onboarding_completed_at FROM auth.users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Currency,
		&i.HasCompletedOnboarding,
		&i.TokensRevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingCompletedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, email, role, created_at
FROM auth.users
ORDER BY created_at ASC
`

type ListAllUsersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllUsersRow{}
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE auth.users
SET tokens_revoked_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE auth.users
SET password_hash = $1, updated_at = now()
WHERE id = $2
`

type UpdatePasswordParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE auth.users
SET username = $1, email = $2, currency = $3, updated_at = now()
WHERE id = $4
RETURNING id, username, email, password_hash, role, currency, has_completed_onboarding, tokens_revoked_at, created_at, updated_at, onboarding_completed_at
`

type UpdateUserParams struct {
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Currency string      `json:"currency"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Currency,
		arg.ID,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Currency,
		&i.HasCompletedOnboarding,
		&i.TokensRevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingCompletedAt,
	)
	return i, err
}
