// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthRefreshTokenBlacklist struct {
	Jti       string             `json:"jti"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type AuthUser struct {
	ID                     pgtype.UUID        `json:"id"`
	Username               string             `json:"username"`
	Email                  string             `json:"email"`
	PasswordHash           string             `json:"password_hash"`
	Role                   string             `json:"role"`
	Currency               string             `json:"currency"`
	HasCompletedOnboarding bool               `json:"has_completed_onboarding"`
	TokensRevokedAt        pgtype.Timestamptz `json:"tokens_revoked_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}
