// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTagInProRata = `-- name: CountTagInProRata :one
SELECT count(*) FROM finance.pro_rata_schedules
WHERE tag_id = $1 AND user_id = $2 AND status = 'pending'
`

type CountTagInProRataParams struct {
	TagID  pgtype.UUID `json:"tag_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountTagInProRata(ctx context.Context, arg CountTagInProRataParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTagInProRata, arg.TagID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserTags = `-- name: CountUserTags :one
SELECT count(*) FROM finance.tags WHERE user_id = $1
`

func (q *Queries) CountUserTags(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTags, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPeriod = `-- name: CreatePeriod :one
INSERT INTO finance.budget_periods
    (user_id, year, month, budget_amount, reporting_currency, essentials_percent, desires_percent, savings_percent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, year, month, budget_amount, reporting_currency, essentials_percent, desires_percent, savings_percent, created_at, updated_at
`

type CreatePeriodParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	Year              int32       `json:"year"`
	Month             int32       `json:"month"`
	BudgetAmount      int64       `json:"budget_amount"`
	ReportingCurrency string      `json:"reporting_currency"`
	EssentialsPercent int32       `json:"essentials_percent"`
	DesiresPercent    int32       `json:"desires_percent"`
	SavingsPercent    int32       `json:"savings_percent"`
}

func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (FinanceBudgetPeriod, error) {
	row := q.db.QueryRow(ctx, createPeriod,
		arg.UserID,
		arg.Year,
		arg.Month,
		arg.BudgetAmount,
		arg.ReportingCurrency,
		arg.EssentialsPercent,
		arg.DesiresPercent,
		arg.SavingsPercent,
	)
	var i FinanceBudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.BudgetAmount,
		&i.ReportingCurrency,
		&i.EssentialsPercent,
		&i.DesiresPercent,
		&i.SavingsPercent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProRataSchedule = `-- name: CreateProRataSchedule :one
INSERT INTO finance.pro_rata_schedules
    (user_id, pro_rata_group, name, amount, currency, expense_type, tag_id,
     target_year, target_month, installment_index, installment_total)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, pro_rata_group, name, amount, currency, expense_type, tag_id, target_year, target_month, installment_index, installment_total, status, created_at, applied_at
`

type CreateProRataScheduleParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	ProRataGroup     pgtype.UUID `json:"pro_rata_group"`
	Name             string      `json:"name"`
	Amount           int64       `json:"amount"`
	Currency         string      `json:"currency"`
	ExpenseType      string      `json:"expense_type"`
	TagID            pgtype.UUID `json:"tag_id"`
	TargetYear       int32       `json:"target_year"`
	TargetMonth      int32       `json:"target_month"`
	InstallmentIndex int32       `json:"installment_index"`
	InstallmentTotal int32       `json:"installment_total"`
}

func (q *Queries) CreateProRataSchedule(ctx context.Context, arg CreateProRataScheduleParams) (FinanceProRataSchedule, error) {
	row := q.db.QueryRow(ctx, createProRataSchedule,
		arg.UserID,
		arg.ProRataGroup,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.ExpenseType,
		arg.TagID,
		arg.TargetYear,
		arg.TargetMonth,
		arg.InstallmentIndex,
		arg.InstallmentTotal,
	)
	var i FinanceProRataSchedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProRataGroup,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.ExpenseType,
		&i.TagID,
		&i.TargetYear,
		&i.TargetMonth,
		&i.InstallmentIndex,
		&i.InstallmentTotal,
		&i.Status,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO finance.tags (user_id, name, is_default)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, is_default, created_at, updated_at
`

type CreateTagParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	IsDefault bool        `json:"is_default"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (FinanceTag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name, arg.IsDefault)
	var i FinanceTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllUserBudgetPeriods = `-- name: DeleteAllUserBudgetPeriods :exec
DELETE FROM finance.budget_periods WHERE user_id = $1
`

func (q *Queries) DeleteAllUserBudgetPeriods(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserBudgetPeriods, userID)
	return err
}

const deleteAllUserDefaultSettings = `-- name: DeleteAllUserDefaultSettings :exec
DELETE FROM finance.default_settings WHERE user_id = $1
`

func (q *Queries) DeleteAllUserDefaultSettings(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserDefaultSettings, userID)
	return err
}

const deleteAllUserHealthScores = `-- name: DeleteAllUserHealthScores :exec
DELETE FROM finance.health_scores WHERE user_id = $1
`

func (q *Queries) DeleteAllUserHealthScores(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserHealthScores, userID)
	return err
}

const deleteAllUserProRataSchedules = `-- name: DeleteAllUserProRataSchedules :exec
DELETE FROM finance.pro_rata_schedules WHERE user_id = $1
`

func (q *Queries) DeleteAllUserProRataSchedules(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserProRataSchedules, userID)
	return err
}

const deleteAllUserTags = `-- name: DeleteAllUserTags :exec
DELETE FROM finance.tags WHERE user_id = $1
`

func (q *Queries) DeleteAllUserTags(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserTags, userID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM finance.tags WHERE id = $1 AND user_id = $2 AND is_default = false
`

type DeleteTagParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const getCurrentPeriod = `-- name: GetCurrentPeriod :one
SELECT id, user_id, year, month, budget_amount, reporting_currency, essentials_percent, desires_percent, savings_percent, created_at, updated_at FROM finance.budget_periods
WHERE user_id = $1 AND year = $2 AND month = $3
`

type GetCurrentPeriodParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Year   int32       `json:"year"`
	Month  int32       `json:"month"`
}

func (q *Queries) GetCurrentPeriod(ctx context.Context, arg GetCurrentPeriodParams) (FinanceBudgetPeriod, error) {
	row := q.db.QueryRow(ctx, getCurrentPeriod, arg.UserID, arg.Year, arg.Month)
	var i FinanceBudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.BudgetAmount,
		&i.ReportingCurrency,
		&i.EssentialsPercent,
		&i.DesiresPercent,
		&i.SavingsPercent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaults = `-- name: GetDefaults :one
SELECT user_id, budget_amount, essentials_percent, desires_percent, savings_percent, currency, created_at, updated_at FROM finance.default_settings WHERE user_id = $1
`

func (q *Queries) GetDefaults(ctx context.Context, userID pgtype.UUID) (FinanceDefaultSetting, error) {
	row := q.db.QueryRow(ctx, getDefaults, userID)
	var i FinanceDefaultSetting
	err := row.Scan(
		&i.UserID,
		&i.BudgetAmount,
		&i.EssentialsPercent,
		&i.DesiresPercent,
		&i.SavingsPercent,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHealthScore = `-- name: GetHealthScore :one
SELECT user_id, year, month, total, band, score, formula_version, computed_at FROM finance.health_scores
WHERE user_id = $1 AND year = $2 AND month = $3
`

type GetHealthScoreParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Year   int32       `json:"year"`
	Month  int32       `json:"month"`
}

func (q *Queries) GetHealthScore(ctx context.Context, arg GetHealthScoreParams) (FinanceHealthScore, error) {
	row := q.db.QueryRow(ctx, getHealthScore, arg.UserID, arg.Year, arg.Month)
	var i FinanceHealthScore
	err := row.Scan(
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.Total,
		&i.Band,
		&i.Score,
		&i.FormulaVersion,
		&i.ComputedAt,
	)
	return i, err
}

const getLatestPeriod = `-- name: GetLatestPeriod :one
SELECT id, user_id, year, month, budget_amount, reporting_currency, essentials_percent, desires_percent, savings_percent, created_at, updated_at FROM finance.budget_periods
WHERE user_id = $1
ORDER BY year DESC, month DESC
LIMIT 1
`

func (q *Queries) GetLatestPeriod(ctx context.Context, userID pgtype.UUID) (FinanceBudgetPeriod, error) {
	row := q.db.QueryRow(ctx, getLatestPeriod, userID)
	var i FinanceBudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.BudgetAmount,
		&i.ReportingCurrency,
		&i.EssentialsPercent,
		&i.DesiresPercent,
		&i.SavingsPercent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingProRata = `-- name: GetPendingProRata :many
SELECT id, user_id, pro_rata_group, name, amount, currency, expense_type, tag_id, target_year, target_month, installment_index, installment_total, status, created_at, applied_at FROM finance.pro_rata_schedules
WHERE user_id = $1 AND target_year = $2 AND target_month = $3 AND status = 'pending'
ORDER BY installment_index ASC
`

type GetPendingProRataParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	TargetYear  int32       `json:"target_year"`
	TargetMonth int32       `json:"target_month"`
}

func (q *Queries) GetPendingProRata(ctx context.Context, arg GetPendingProRataParams) ([]FinanceProRataSchedule, error) {
	rows, err := q.db.Query(ctx, getPendingProRata, arg.UserID, arg.TargetYear, arg.TargetMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceProRataSchedule{}
	for rows.Next() {
		var i FinanceProRataSchedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProRataGroup,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.ExpenseType,
			&i.TagID,
			&i.TargetYear,
			&i.TargetMonth,
			&i.InstallmentIndex,
			&i.InstallmentTotal,
			&i.Status,
			&i.CreatedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeriodByID = `-- name: GetPeriodByID :one
SELECT id, user_id, year, month, budget_amount, reporting_currency, essentials_percent, desires_percent, savings_percent, created_at, updated_at FROM finance.budget_periods
WHERE id = $1 AND user_id = $2
`

type GetPeriodByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetPeriodByID(ctx context.Context, arg GetPeriodByIDParams) (FinanceBudgetPeriod, error) {
	row := q.db.QueryRow(ctx, getPeriodByID, arg.ID, arg.UserID)
	var i FinanceBudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.BudgetAmount,
		&i.ReportingCurrency,
		&i.EssentialsPercent,
		&i.DesiresPercent,
		&i.SavingsPercent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, user_id, name, is_default, created_at, updated_at FROM finance.tags
WHERE id = $1 AND user_id = $2
`

type GetTagByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTagByID(ctx context.Context, arg GetTagByIDParams) (FinanceTag, error) {
	row := q.db.QueryRow(ctx, getTagByID, arg.ID, arg.UserID)
	var i FinanceTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpcomingProRata = `-- name: GetUpcomingProRata :many
SELECT id, user_id, pro_rata_group, name, amount, currency, expense_type, tag_id, target_year, target_month, installment_index, installment_total, status, created_at, applied_at FROM finance.pro_rata_schedules
WHERE user_id = $1 AND status = 'pending'
ORDER BY target_year ASC, target_month ASC, installment_index ASC
`

func (q *Queries) GetUpcomingProRata(ctx context.Context, userID pgtype.UUID) ([]FinanceProRataSchedule, error) {
	rows, err := q.db.Query(ctx, getUpcomingProRata, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceProRataSchedule{}
	for rows.Next() {
		var i FinanceProRataSchedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProRataGroup,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.ExpenseType,
			&i.TagID,
			&i.TargetYear,
			&i.TargetMonth,
			&i.InstallmentIndex,
			&i.InstallmentTotal,
			&i.Status,
			&i.CreatedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHealthScoreScalars = `-- name: ListHealthScoreScalars :many
SELECT year, month, total, band, formula_version
FROM finance.health_scores
WHERE user_id = $1
ORDER BY year DESC, month DESC
`

type ListHealthScoreScalarsRow struct {
	Year           int32  `json:"year"`
	Month          int32  `json:"month"`
	Total          int32  `json:"total"`
	Band           string `json:"band"`
	FormulaVersion int32  `json:"formula_version"`
}

// Denormalized scalar columns only (no score JSONB) for the trend read; served
// by idx_health_scores_user (user_id, year DESC, month DESC).
func (q *Queries) ListHealthScoreScalars(ctx context.Context, userID pgtype.UUID) ([]ListHealthScoreScalarsRow, error) {
	rows, err := q.db.Query(ctx, listHealthScoreScalars, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHealthScoreScalarsRow{}
	for rows.Next() {
		var i ListHealthScoreScalarsRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.Total,
			&i.Band,
			&i.FormulaVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriods = `-- name: ListPeriods :many
SELECT id, user_id, year, month, budget_amount, reporting_currency, essentials_percent, desires_percent, savings_percent, created_at, updated_at FROM finance.budget_periods
WHERE user_id = $1
ORDER BY year DESC, month DESC
`

func (q *Queries) ListPeriods(ctx context.Context, userID pgtype.UUID) ([]FinanceBudgetPeriod, error) {
	rows, err := q.db.Query(ctx, listPeriods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceBudgetPeriod{}
	for rows.Next() {
		var i FinanceBudgetPeriod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Year,
			&i.Month,
			&i.BudgetAmount,
			&i.ReportingCurrency,
			&i.EssentialsPercent,
			&i.DesiresPercent,
			&i.SavingsPercent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, user_id, name, is_default, created_at, updated_at FROM finance.tags
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context, userID pgtype.UUID) ([]FinanceTag, error) {
	rows, err := q.db.Query(ctx, listTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceTag{}
	for rows.Next() {
		var i FinanceTag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProRataApplied = `-- name: MarkProRataApplied :exec
UPDATE finance.pro_rata_schedules
SET status = 'applied', applied_at = now()
WHERE id = $1
`

func (q *Queries) MarkProRataApplied(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markProRataApplied, id)
	return err
}

const updatePeriod = `-- name: UpdatePeriod :one
UPDATE finance.budget_periods
SET budget_amount = $1, essentials_percent = $2, desires_percent = $3,
    savings_percent = $4, updated_at = now()
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, year, month, budget_amount, reporting_currency, essentials_percent, desires_percent, savings_percent, created_at, updated_at
`

type UpdatePeriodParams struct {
	BudgetAmount      int64       `json:"budget_amount"`
	EssentialsPercent int32       `json:"essentials_percent"`
	DesiresPercent    int32       `json:"desires_percent"`
	SavingsPercent    int32       `json:"savings_percent"`
	ID                pgtype.UUID `json:"id"`
	UserID            pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdatePeriod(ctx context.Context, arg UpdatePeriodParams) (FinanceBudgetPeriod, error) {
	row := q.db.QueryRow(ctx, updatePeriod,
		arg.BudgetAmount,
		arg.EssentialsPercent,
		arg.DesiresPercent,
		arg.SavingsPercent,
		arg.ID,
		arg.UserID,
	)
	var i FinanceBudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.BudgetAmount,
		&i.ReportingCurrency,
		&i.EssentialsPercent,
		&i.DesiresPercent,
		&i.SavingsPercent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE finance.tags SET name = $1, updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, name, is_default, created_at, updated_at
`

type UpdateTagParams struct {
	Name   string      `json:"name"`
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (FinanceTag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.Name, arg.ID, arg.UserID)
	var i FinanceTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDefaults = `-- name: UpsertDefaults :one
INSERT INTO finance.default_settings
    (user_id, budget_amount, essentials_percent, desires_percent, savings_percent, currency)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id)
DO UPDATE SET
    budget_amount = EXCLUDED.budget_amount,
    essentials_percent = EXCLUDED.essentials_percent,
    desires_percent = EXCLUDED.desires_percent,
    savings_percent = EXCLUDED.savings_percent,
    currency = EXCLUDED.currency,
    updated_at = now()
RETURNING user_id, budget_amount, essentials_percent, desires_percent, savings_percent, currency, created_at, updated_at
`

type UpsertDefaultsParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	BudgetAmount      int64       `json:"budget_amount"`
	EssentialsPercent int32       `json:"essentials_percent"`
	DesiresPercent    int32       `json:"desires_percent"`
	SavingsPercent    int32       `json:"savings_percent"`
	Currency          string      `json:"currency"`
}

func (q *Queries) UpsertDefaults(ctx context.Context, arg UpsertDefaultsParams) (FinanceDefaultSetting, error) {
	row := q.db.QueryRow(ctx, upsertDefaults,
		arg.UserID,
		arg.BudgetAmount,
		arg.EssentialsPercent,
		arg.DesiresPercent,
		arg.SavingsPercent,
		arg.Currency,
	)
	var i FinanceDefaultSetting
	err := row.Scan(
		&i.UserID,
		&i.BudgetAmount,
		&i.EssentialsPercent,
		&i.DesiresPercent,
		&i.SavingsPercent,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHealthScore = `-- name: UpsertHealthScore :one
INSERT INTO finance.health_scores
    (user_id, year, month, total, band, score, formula_version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, year, month)
DO UPDATE SET
    total = EXCLUDED.total,
    band = EXCLUDED.band,
    score = EXCLUDED.score,
    formula_version = EXCLUDED.formula_version,
    computed_at = now()
RETURNING user_id, year, month, total, band, score, formula_version, computed_at
`

type UpsertHealthScoreParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Year           int32       `json:"year"`
	Month          int32       `json:"month"`
	Total          int32       `json:"total"`
	Band           string      `json:"band"`
	Score          []byte      `json:"score"`
	FormulaVersion int32       `json:"formula_version"`
}

func (q *Queries) UpsertHealthScore(ctx context.Context, arg UpsertHealthScoreParams) (FinanceHealthScore, error) {
	row := q.db.QueryRow(ctx, upsertHealthScore,
		arg.UserID,
		arg.Year,
		arg.Month,
		arg.Total,
		arg.Band,
		arg.Score,
		arg.FormulaVersion,
	)
	var i FinanceHealthScore
	err := row.Scan(
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.Total,
		&i.Band,
		&i.Score,
		&i.FormulaVersion,
		&i.ComputedAt,
	)
	return i, err
}
