// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FinanceBudgetPeriod struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Year              int32              `json:"year"`
	Month             int32              `json:"month"`
	BudgetAmount      int64              `json:"budget_amount"`
	EssentialsPercent int32              `json:"essentials_percent"`
	DesiresPercent    int32              `json:"desires_percent"`
	SavingsPercent    int32              `json:"savings_percent"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type FinanceDefaultSetting struct {
	UserID            pgtype.UUID        `json:"user_id"`
	BudgetAmount      int64              `json:"budget_amount"`
	EssentialsPercent int32              `json:"essentials_percent"`
	DesiresPercent    int32              `json:"desires_percent"`
	SavingsPercent    int32              `json:"savings_percent"`
	Currency          string             `json:"currency"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type FinanceProRataSchedule struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	ProRataGroup     pgtype.UUID        `json:"pro_rata_group"`
	Name             string             `json:"name"`
	Amount           int64              `json:"amount"`
	Currency         string             `json:"currency"`
	ExpenseType      string             `json:"expense_type"`
	TagID            pgtype.UUID        `json:"tag_id"`
	TargetYear       int32              `json:"target_year"`
	TargetMonth      int32              `json:"target_month"`
	InstallmentIndex int32              `json:"installment_index"`
	InstallmentTotal int32              `json:"installment_total"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
}

type FinanceTag struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
