// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: proto/reporting.proto

package reportingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricErrorCode int32

const (
	MetricErrorCode_METRIC_ERROR_CODE_UNSPECIFIED    MetricErrorCode = 0
	MetricErrorCode_METRIC_ERROR_CODE_QUERY_FAILED   MetricErrorCode = 1
	MetricErrorCode_METRIC_ERROR_CODE_INVALID_WINDOW MetricErrorCode = 2
	MetricErrorCode_METRIC_ERROR_CODE_INTERNAL       MetricErrorCode = 3
)

// Enum value maps for MetricErrorCode.
var (
	MetricErrorCode_name = map[int32]string{
		0: "METRIC_ERROR_CODE_UNSPECIFIED",
		1: "METRIC_ERROR_CODE_QUERY_FAILED",
		2: "METRIC_ERROR_CODE_INVALID_WINDOW",
		3: "METRIC_ERROR_CODE_INTERNAL",
	}
	MetricErrorCode_value = map[string]int32{
		"METRIC_ERROR_CODE_UNSPECIFIED":    0,
		"METRIC_ERROR_CODE_QUERY_FAILED":   1,
		"METRIC_ERROR_CODE_INVALID_WINDOW": 2,
		"METRIC_ERROR_CODE_INTERNAL":       3,
	}
)

func (x MetricErrorCode) Enum() *MetricErrorCode {
	p := new(MetricErrorCode)
	*p = x
	return p
}

func (x MetricErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reporting_proto_enumTypes[0].Descriptor()
}

func (MetricErrorCode) Type() protoreflect.EnumType {
	return &file_proto_reporting_proto_enumTypes[0]
}

func (x MetricErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricErrorCode.Descriptor instead.
func (MetricErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{0}
}

type UtcWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtcWindow) Reset() {
	*x = UtcWindow{}
	mi := &file_proto_reporting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtcWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtcWindow) ProtoMessage() {}

func (x *UtcWindow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtcWindow.ProtoReflect.Descriptor instead.
func (*UtcWindow) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{0}
}

func (x *UtcWindow) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *UtcWindow) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ReportWindowSet struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RequestedReportWeekStart *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=requested_report_week_start,json=requestedReportWeekStart,proto3" json:"requested_report_week_start,omitempty"`
	ReportWeek               *UtcWindow             `protobuf:"bytes,2,opt,name=report_week,json=reportWeek,proto3" json:"report_week,omitempty"`
	PreviousWeek             *UtcWindow             `protobuf:"bytes,3,opt,name=previous_week,json=previousWeek,proto3" json:"previous_week,omitempty"`
	TrailingFourWeeks        *UtcWindow             `protobuf:"bytes,4,opt,name=trailing_four_weeks,json=trailingFourWeeks,proto3" json:"trailing_four_weeks,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ReportWindowSet) Reset() {
	*x = ReportWindowSet{}
	mi := &file_proto_reporting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportWindowSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportWindowSet) ProtoMessage() {}

func (x *ReportWindowSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportWindowSet.ProtoReflect.Descriptor instead.
func (*ReportWindowSet) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{1}
}

func (x *ReportWindowSet) GetRequestedReportWeekStart() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedReportWeekStart
	}
	return nil
}

func (x *ReportWindowSet) GetReportWeek() *UtcWindow {
	if x != nil {
		return x.ReportWeek
	}
	return nil
}

func (x *ReportWindowSet) GetPreviousWeek() *UtcWindow {
	if x != nil {
		return x.PreviousWeek
	}
	return nil
}

func (x *ReportWindowSet) GetTrailingFourWeeks() *UtcWindow {
	if x != nil {
		return x.TrailingFourWeeks
	}
	return nil
}

type CountValues struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ReportWeek             int64                  `protobuf:"varint,1,opt,name=report_week,json=reportWeek,proto3" json:"report_week,omitempty"`
	PreviousWeek           int64                  `protobuf:"varint,2,opt,name=previous_week,json=previousWeek,proto3" json:"previous_week,omitempty"`
	TrailingFourWeeksTotal int64                  `protobuf:"varint,3,opt,name=trailing_four_weeks_total,json=trailingFourWeeksTotal,proto3" json:"trailing_four_weeks_total,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CountValues) Reset() {
	*x = CountValues{}
	mi := &file_proto_reporting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountValues) ProtoMessage() {}

func (x *CountValues) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountValues.ProtoReflect.Descriptor instead.
func (*CountValues) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{2}
}

func (x *CountValues) GetReportWeek() int64 {
	if x != nil {
		return x.ReportWeek
	}
	return 0
}

func (x *CountValues) GetPreviousWeek() int64 {
	if x != nil {
		return x.PreviousWeek
	}
	return 0
}

func (x *CountValues) GetTrailingFourWeeksTotal() int64 {
	if x != nil {
		return x.TrailingFourWeeksTotal
	}
	return 0
}

type MetricUnavailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          MetricErrorCode        `protobuf:"varint,1,opt,name=code,proto3,enum=reporting.MetricErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricUnavailable) Reset() {
	*x = MetricUnavailable{}
	mi := &file_proto_reporting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricUnavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricUnavailable) ProtoMessage() {}

func (x *MetricUnavailable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricUnavailable.ProtoReflect.Descriptor instead.
func (*MetricUnavailable) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{3}
}

func (x *MetricUnavailable) GetCode() MetricErrorCode {
	if x != nil {
		return x.Code
	}
	return MetricErrorCode_METRIC_ERROR_CODE_UNSPECIFIED
}

type CountResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to State:
	//
	//	*CountResult_Available
	//	*CountResult_Unavailable
	State         isCountResult_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResult) Reset() {
	*x = CountResult{}
	mi := &file_proto_reporting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResult) ProtoMessage() {}

func (x *CountResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResult.ProtoReflect.Descriptor instead.
func (*CountResult) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{4}
}

func (x *CountResult) GetState() isCountResult_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *CountResult) GetAvailable() *CountValues {
	if x != nil {
		if x, ok := x.State.(*CountResult_Available); ok {
			return x.Available
		}
	}
	return nil
}

func (x *CountResult) GetUnavailable() *MetricUnavailable {
	if x != nil {
		if x, ok := x.State.(*CountResult_Unavailable); ok {
			return x.Unavailable
		}
	}
	return nil
}

type isCountResult_State interface {
	isCountResult_State()
}

type CountResult_Available struct {
	Available *CountValues `protobuf:"bytes,1,opt,name=available,proto3,oneof"`
}

type CountResult_Unavailable struct {
	Unavailable *MetricUnavailable `protobuf:"bytes,2,opt,name=unavailable,proto3,oneof"`
}

func (*CountResult_Available) isCountResult_State() {}

func (*CountResult_Unavailable) isCountResult_State() {}

var File_proto_reporting_proto protoreflect.FileDescriptor

const file_proto_reporting_proto_rawDesc = "" +
	"\n" +
	"\x15proto/reporting.proto\x12\treporting\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\tUtcWindow\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xa4\x02\n" +
	"\x0fReportWindowSet\x12Y\n" +
	"\x1brequested_report_week_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x18requestedReportWeekStart\x125\n" +
	"\vreport_week\x18\x02 \x01(\v2\x14.reporting.UtcWindowR\n" +
	"reportWeek\x129\n" +
	"\rprevious_week\x18\x03 \x01(\v2\x14.reporting.UtcWindowR\fpreviousWeek\x12D\n" +
	"\x13trailing_four_weeks\x18\x04 \x01(\v2\x14.reporting.UtcWindowR\x11trailingFourWeeks\"\x8e\x01\n" +
	"\vCountValues\x12\x1f\n" +
	"\vreport_week\x18\x01 \x01(\x03R\n" +
	"reportWeek\x12#\n" +
	"\rprevious_week\x18\x02 \x01(\x03R\fpreviousWeek\x129\n" +
	"\x19trailing_four_weeks_total\x18\x03 \x01(\x03R\x16trailingFourWeeksTotal\"C\n" +
	"\x11MetricUnavailable\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.reporting.MetricErrorCodeR\x04code\"\x90\x01\n" +
	"\vCountResult\x126\n" +
	"\tavailable\x18\x01 \x01(\v2\x16.reporting.CountValuesH\x00R\tavailable\x12@\n" +
	"\vunavailable\x18\x02 \x01(\v2\x1c.reporting.MetricUnavailableH\x00R\vunavailableB\a\n" +
	"\x05state*\x9e\x01\n" +
	"\x0fMetricErrorCode\x12!\n" +
	"\x1dMETRIC_ERROR_CODE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eMETRIC_ERROR_CODE_QUERY_FAILED\x10\x01\x12$\n" +
	" METRIC_ERROR_CODE_INVALID_WINDOW\x10\x02\x12\x1e\n" +
	"\x1aMETRIC_ERROR_CODE_INTERNAL\x10\x03BJZHgithub.com/ItsThompson/gofin/services/shared/reporting/proto/reportingpbb\x06proto3"

var (
	file_proto_reporting_proto_rawDescOnce sync.Once
	file_proto_reporting_proto_rawDescData []byte
)

func file_proto_reporting_proto_rawDescGZIP() []byte {
	file_proto_reporting_proto_rawDescOnce.Do(func() {
		file_proto_reporting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reporting_proto_rawDesc), len(file_proto_reporting_proto_rawDesc)))
	})
	return file_proto_reporting_proto_rawDescData
}

var file_proto_reporting_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_reporting_proto_goTypes = []any{
	(MetricErrorCode)(0),          // 0: reporting.MetricErrorCode
	(*UtcWindow)(nil),             // 1: reporting.UtcWindow
	(*ReportWindowSet)(nil),       // 2: reporting.ReportWindowSet
	(*CountValues)(nil),           // 3: reporting.CountValues
	(*MetricUnavailable)(nil),     // 4: reporting.MetricUnavailable
	(*CountResult)(nil),           // 5: reporting.CountResult
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_reporting_proto_depIdxs = []int32{
	6, // 0: reporting.UtcWindow.start:type_name -> google.protobuf.Timestamp
	6, // 1: reporting.UtcWindow.end:type_name -> google.protobuf.Timestamp
	6, // 2: reporting.ReportWindowSet.requested_report_week_start:type_name -> google.protobuf.Timestamp
	1, // 3: reporting.ReportWindowSet.report_week:type_name -> reporting.UtcWindow
	1, // 4: reporting.ReportWindowSet.previous_week:type_name -> reporting.UtcWindow
	1, // 5: reporting.ReportWindowSet.trailing_four_weeks:type_name -> reporting.UtcWindow
	0, // 6: reporting.MetricUnavailable.code:type_name -> reporting.MetricErrorCode
	3, // 7: reporting.CountResult.available:type_name -> reporting.CountValues
	4, // 8: reporting.CountResult.unavailable:type_name -> reporting.MetricUnavailable
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_reporting_proto_init() }
func file_proto_reporting_proto_init() {
	if File_proto_reporting_proto != nil {
		return
	}
	file_proto_reporting_proto_msgTypes[4].OneofWrappers = []any{
		(*CountResult_Available)(nil),
		(*CountResult_Unavailable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reporting_proto_rawDesc), len(file_proto_reporting_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_reporting_proto_goTypes,
		DependencyIndexes: file_proto_reporting_proto_depIdxs,
		EnumInfos:         file_proto_reporting_proto_enumTypes,
		MessageInfos:      file_proto_reporting_proto_msgTypes,
	}.Build()
	File_proto_reporting_proto = out.File
	file_proto_reporting_proto_goTypes = nil
	file_proto_reporting_proto_depIdxs = nil
}
