// Code generated by scripts/generate-currency-catalog.mjs; DO NOT EDIT.

package currency

// Definition describes one supported currency.
type Definition struct {
	Code            string
	Symbol          string
	Name            string
	MinorUnitDigits int
}

var supportedCurrencies = []Definition{
	{Code: "USD", Symbol: "$", Name: "US Dollar", MinorUnitDigits: 2},
	{Code: "EUR", Symbol: "€", Name: "Euro", MinorUnitDigits: 2},
	{Code: "GBP", Symbol: "£", Name: "British Pound", MinorUnitDigits: 2},
	{Code: "JPY", Symbol: "¥", Name: "Japanese Yen", MinorUnitDigits: 0},
	{Code: "CAD", Symbol: "C$", Name: "Canadian Dollar", MinorUnitDigits: 2},
	{Code: "AUD", Symbol: "A$", Name: "Australian Dollar", MinorUnitDigits: 2},
	{Code: "CHF", Symbol: "CHF", Name: "Swiss Franc", MinorUnitDigits: 2},
	{Code: "CNY", Symbol: "¥", Name: "Chinese Yuan", MinorUnitDigits: 2},
	{Code: "SGD", Symbol: "S$", Name: "Singapore Dollar", MinorUnitDigits: 2},
	{Code: "HKD", Symbol: "HK$", Name: "Hong Kong Dollar", MinorUnitDigits: 2},
}

var catalog = map[string]Definition{
	"USD": {Code: "USD", Symbol: "$", Name: "US Dollar", MinorUnitDigits: 2},
	"EUR": {Code: "EUR", Symbol: "€", Name: "Euro", MinorUnitDigits: 2},
	"GBP": {Code: "GBP", Symbol: "£", Name: "British Pound", MinorUnitDigits: 2},
	"JPY": {Code: "JPY", Symbol: "¥", Name: "Japanese Yen", MinorUnitDigits: 0},
	"CAD": {Code: "CAD", Symbol: "C$", Name: "Canadian Dollar", MinorUnitDigits: 2},
	"AUD": {Code: "AUD", Symbol: "A$", Name: "Australian Dollar", MinorUnitDigits: 2},
	"CHF": {Code: "CHF", Symbol: "CHF", Name: "Swiss Franc", MinorUnitDigits: 2},
	"CNY": {Code: "CNY", Symbol: "¥", Name: "Chinese Yuan", MinorUnitDigits: 2},
	"SGD": {Code: "SGD", Symbol: "S$", Name: "Singapore Dollar", MinorUnitDigits: 2},
	"HKD": {Code: "HKD", Symbol: "HK$", Name: "Hong Kong Dollar", MinorUnitDigits: 2},
}

func All() []Definition {
	definitions := make([]Definition, len(supportedCurrencies))
	copy(definitions, supportedCurrencies)
	return definitions
}

func Get(code string) (Definition, bool) {
	definition, ok := catalog[code]
	return definition, ok
}

func IsSupported(code string) bool {
	_, ok := catalog[code]
	return ok
}
