// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/fx.proto

package fxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaptureRateSnapshotRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequiredCurrencies []string               `protobuf:"bytes,1,rep,name=required_currencies,json=requiredCurrencies,proto3" json:"required_currencies,omitempty"`
	RequestedAt        string                 `protobuf:"bytes,2,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CaptureRateSnapshotRequest) Reset() {
	*x = CaptureRateSnapshotRequest{}
	mi := &file_proto_fx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRateSnapshotRequest) ProtoMessage() {}

func (x *CaptureRateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CaptureRateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_fx_proto_rawDescGZIP(), []int{0}
}

func (x *CaptureRateSnapshotRequest) GetRequiredCurrencies() []string {
	if x != nil {
		return x.RequiredCurrencies
	}
	return nil
}

func (x *CaptureRateSnapshotRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type CaptureRateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *CapturedRateSnapshot  `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	CacheStatus   string                 `protobuf:"bytes,2,opt,name=cache_status,json=cacheStatus,proto3" json:"cache_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureRateSnapshotResponse) Reset() {
	*x = CaptureRateSnapshotResponse{}
	mi := &file_proto_fx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRateSnapshotResponse) ProtoMessage() {}

func (x *CaptureRateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CaptureRateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_fx_proto_rawDescGZIP(), []int{1}
}

func (x *CaptureRateSnapshotResponse) GetSnapshot() *CapturedRateSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *CaptureRateSnapshotResponse) GetCacheStatus() string {
	if x != nil {
		return x.CacheStatus
	}
	return ""
}

type CapturedRateSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotVersion int32                  `protobuf:"varint,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	BaseCurrency    string                 `protobuf:"bytes,3,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	RateTimestamp   string                 `protobuf:"bytes,4,opt,name=rate_timestamp,json=rateTimestamp,proto3" json:"rate_timestamp,omitempty"`
	CapturedAt      string                 `protobuf:"bytes,5,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RatesByCurrency map[string]string      `protobuf:"bytes,7,rep,name=rates_by_currency,json=ratesByCurrency,proto3" json:"rates_by_currency,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapturedRateSnapshot) Reset() {
	*x = CapturedRateSnapshot{}
	mi := &file_proto_fx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturedRateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturedRateSnapshot) ProtoMessage() {}

func (x *CapturedRateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturedRateSnapshot.ProtoReflect.Descriptor instead.
func (*CapturedRateSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_fx_proto_rawDescGZIP(), []int{2}
}

func (x *CapturedRateSnapshot) GetSnapshotVersion() int32 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

func (x *CapturedRateSnapshot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CapturedRateSnapshot) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *CapturedRateSnapshot) GetRateTimestamp() string {
	if x != nil {
		return x.RateTimestamp
	}
	return ""
}

func (x *CapturedRateSnapshot) GetCapturedAt() string {
	if x != nil {
		return x.CapturedAt
	}
	return ""
}

func (x *CapturedRateSnapshot) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CapturedRateSnapshot) GetRatesByCurrency() map[string]string {
	if x != nil {
		return x.RatesByCurrency
	}
	return nil
}

type ConvertAmountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Amount         int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	SourceCurrency string                 `protobuf:"bytes,2,opt,name=source_currency,json=sourceCurrency,proto3" json:"source_currency,omitempty"`
	TargetCurrency string                 `protobuf:"bytes,3,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	RequestedAt    string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConvertAmountRequest) Reset() {
	*x = ConvertAmountRequest{}
	mi := &file_proto_fx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAmountRequest) ProtoMessage() {}

func (x *ConvertAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAmountRequest.ProtoReflect.Descriptor instead.
func (*ConvertAmountRequest) Descriptor() ([]byte, []int) {
	return file_proto_fx_proto_rawDescGZIP(), []int{3}
}

func (x *ConvertAmountRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConvertAmountRequest) GetSourceCurrency() string {
	if x != nil {
		return x.SourceCurrency
	}
	return ""
}

func (x *ConvertAmountRequest) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

func (x *ConvertAmountRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type ConvertWithSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Amount         int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	SourceCurrency string                 `protobuf:"bytes,2,opt,name=source_currency,json=sourceCurrency,proto3" json:"source_currency,omitempty"`
	TargetCurrency string                 `protobuf:"bytes,3,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	RequestedAt    string                 `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	Snapshot       *CapturedRateSnapshot  `protobuf:"bytes,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConvertWithSnapshotRequest) Reset() {
	*x = ConvertWithSnapshotRequest{}
	mi := &file_proto_fx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertWithSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertWithSnapshotRequest) ProtoMessage() {}

func (x *ConvertWithSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertWithSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ConvertWithSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_fx_proto_rawDescGZIP(), []int{4}
}

func (x *ConvertWithSnapshotRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConvertWithSnapshotRequest) GetSourceCurrency() string {
	if x != nil {
		return x.SourceCurrency
	}
	return ""
}

func (x *ConvertWithSnapshotRequest) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

func (x *ConvertWithSnapshotRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

func (x *ConvertWithSnapshotRequest) GetSnapshot() *CapturedRateSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ConvertAmountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConvertedAmount int64                  `protobuf:"varint,1,opt,name=converted_amount,json=convertedAmount,proto3" json:"converted_amount,omitempty"`
	SourceCurrency  string                 `protobuf:"bytes,2,opt,name=source_currency,json=sourceCurrency,proto3" json:"source_currency,omitempty"`
	TargetCurrency  string                 `protobuf:"bytes,3,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	ExchangeRate    string                 `protobuf:"bytes,4,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	RateTimestamp   string                 `protobuf:"bytes,5,opt,name=rate_timestamp,json=rateTimestamp,proto3" json:"rate_timestamp,omitempty"`
	Source          string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	CacheStatus     string                 `protobuf:"bytes,7,opt,name=cache_status,json=cacheStatus,proto3" json:"cache_status,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConvertAmountResponse) Reset() {
	*x = ConvertAmountResponse{}
	mi := &file_proto_fx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAmountResponse) ProtoMessage() {}

func (x *ConvertAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAmountResponse.ProtoReflect.Descriptor instead.
func (*ConvertAmountResponse) Descriptor() ([]byte, []int) {
	return file_proto_fx_proto_rawDescGZIP(), []int{5}
}

func (x *ConvertAmountResponse) GetConvertedAmount() int64 {
	if x != nil {
		return x.ConvertedAmount
	}
	return 0
}

func (x *ConvertAmountResponse) GetSourceCurrency() string {
	if x != nil {
		return x.SourceCurrency
	}
	return ""
}

func (x *ConvertAmountResponse) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

func (x *ConvertAmountResponse) GetExchangeRate() string {
	if x != nil {
		return x.ExchangeRate
	}
	return ""
}

func (x *ConvertAmountResponse) GetRateTimestamp() string {
	if x != nil {
		return x.RateTimestamp
	}
	return ""
}

func (x *ConvertAmountResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ConvertAmountResponse) GetCacheStatus() string {
	if x != nil {
		return x.CacheStatus
	}
	return ""
}

func (x *ConvertAmountResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_proto_fx_proto protoreflect.FileDescriptor

const file_proto_fx_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/fx.proto\x12\x02fx\"p\n" +
	"\x1aCaptureRateSnapshotRequest\x12/\n" +
	"\x13required_currencies\x18\x01 \x03(\tR\x12requiredCurrencies\x12!\n" +
	"\frequested_at\x18\x02 \x01(\tR\vrequestedAt\"v\n" +
	"\x1bCaptureRateSnapshotResponse\x124\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x18.fx.CapturedRateSnapshotR\bsnapshot\x12!\n" +
	"\fcache_status\x18\x02 \x01(\tR\vcacheStatus\"\x84\x03\n" +
	"\x14CapturedRateSnapshot\x12)\n" +
	"\x10snapshot_version\x18\x01 \x01(\x05R\x0fsnapshotVersion\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12#\n" +
	"\rbase_currency\x18\x03 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0erate_timestamp\x18\x04 \x01(\tR\rrateTimestamp\x12\x1f\n" +
	"\vcaptured_at\x18\x05 \x01(\tR\n" +
	"capturedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\x12Y\n" +
	"\x11rates_by_currency\x18\a \x03(\v2-.fx.CapturedRateSnapshot.RatesByCurrencyEntryR\x0fratesByCurrency\x1aB\n" +
	"\x14RatesByCurrencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x01\n" +
	"\x14ConvertAmountRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12'\n" +
	"\x0fsource_currency\x18\x02 \x01(\tR\x0esourceCurrency\x12'\n" +
	"\x0ftarget_currency\x18\x03 \x01(\tR\x0etargetCurrency\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\"\xdf\x01\n" +
	"\x1aConvertWithSnapshotRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12'\n" +
	"\x0fsource_currency\x18\x02 \x01(\tR\x0esourceCurrency\x12'\n" +
	"\x0ftarget_currency\x18\x03 \x01(\tR\x0etargetCurrency\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAt\x124\n" +
	"\bsnapshot\x18\x05 \x01(\v2\x18.fx.CapturedRateSnapshotR\bsnapshot\"\xba\x02\n" +
	"\x15ConvertAmountResponse\x12)\n" +
	"\x10converted_amount\x18\x01 \x01(\x03R\x0fconvertedAmount\x12'\n" +
	"\x0fsource_currency\x18\x02 \x01(\tR\x0esourceCurrency\x12'\n" +
	"\x0ftarget_currency\x18\x03 \x01(\tR\x0etargetCurrency\x12#\n" +
	"\rexchange_rate\x18\x04 \x01(\tR\fexchangeRate\x12%\n" +
	"\x0erate_timestamp\x18\x05 \x01(\tR\rrateTimestamp\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12!\n" +
	"\fcache_status\x18\a \x01(\tR\vcacheStatus\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt2\xfb\x01\n" +
	"\tFxService\x12V\n" +
	"\x13CaptureRateSnapshot\x12\x1e.fx.CaptureRateSnapshotRequest\x1a\x1f.fx.CaptureRateSnapshotResponse\x12D\n" +
	"\rConvertAmount\x12\x18.fx.ConvertAmountRequest\x1a\x19.fx.ConvertAmountResponse\x12P\n" +
	"\x13ConvertWithSnapshot\x12\x1e.fx.ConvertWithSnapshotRequest\x1a\x19.fx.ConvertAmountResponseB5Z3github.com/ItsThompson/gofin/services/fx/proto/fxpbb\x06proto3"

var (
	file_proto_fx_proto_rawDescOnce sync.Once
	file_proto_fx_proto_rawDescData []byte
)

func file_proto_fx_proto_rawDescGZIP() []byte {
	file_proto_fx_proto_rawDescOnce.Do(func() {
		file_proto_fx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fx_proto_rawDesc), len(file_proto_fx_proto_rawDesc)))
	})
	return file_proto_fx_proto_rawDescData
}

var file_proto_fx_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_fx_proto_goTypes = []any{
	(*CaptureRateSnapshotRequest)(nil),  // 0: fx.CaptureRateSnapshotRequest
	(*CaptureRateSnapshotResponse)(nil), // 1: fx.CaptureRateSnapshotResponse
	(*CapturedRateSnapshot)(nil),        // 2: fx.CapturedRateSnapshot
	(*ConvertAmountRequest)(nil),        // 3: fx.ConvertAmountRequest
	(*ConvertWithSnapshotRequest)(nil),  // 4: fx.ConvertWithSnapshotRequest
	(*ConvertAmountResponse)(nil),       // 5: fx.ConvertAmountResponse
	nil,                                 // 6: fx.CapturedRateSnapshot.RatesByCurrencyEntry
}
var file_proto_fx_proto_depIdxs = []int32{
	2, // 0: fx.CaptureRateSnapshotResponse.snapshot:type_name -> fx.CapturedRateSnapshot
	6, // 1: fx.CapturedRateSnapshot.rates_by_currency:type_name -> fx.CapturedRateSnapshot.RatesByCurrencyEntry
	2, // 2: fx.ConvertWithSnapshotRequest.snapshot:type_name -> fx.CapturedRateSnapshot
	0, // 3: fx.FxService.CaptureRateSnapshot:input_type -> fx.CaptureRateSnapshotRequest
	3, // 4: fx.FxService.ConvertAmount:input_type -> fx.ConvertAmountRequest
	4, // 5: fx.FxService.ConvertWithSnapshot:input_type -> fx.ConvertWithSnapshotRequest
	1, // 6: fx.FxService.CaptureRateSnapshot:output_type -> fx.CaptureRateSnapshotResponse
	5, // 7: fx.FxService.ConvertAmount:output_type -> fx.ConvertAmountResponse
	5, // 8: fx.FxService.ConvertWithSnapshot:output_type -> fx.ConvertAmountResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_fx_proto_init() }
func file_proto_fx_proto_init() {
	if File_proto_fx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fx_proto_rawDesc), len(file_proto_fx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fx_proto_goTypes,
		DependencyIndexes: file_proto_fx_proto_depIdxs,
		MessageInfos:      file_proto_fx_proto_msgTypes,
	}.Build()
	File_proto_fx_proto = out.File
	file_proto_fx_proto_goTypes = nil
	file_proto_fx_proto_depIdxs = nil
}
