// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: proto/fx.proto

package fxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FxService_CaptureRateSnapshot_FullMethodName = "/fx.FxService/CaptureRateSnapshot"
	FxService_ConvertAmount_FullMethodName       = "/fx.FxService/ConvertAmount"
	FxService_ConvertWithSnapshot_FullMethodName = "/fx.FxService/ConvertWithSnapshot"
)

// FxServiceClient is the client API for FxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FxServiceClient interface {
	CaptureRateSnapshot(ctx context.Context, in *CaptureRateSnapshotRequest, opts ...grpc.CallOption) (*CaptureRateSnapshotResponse, error)
	ConvertAmount(ctx context.Context, in *ConvertAmountRequest, opts ...grpc.CallOption) (*ConvertAmountResponse, error)
	ConvertWithSnapshot(ctx context.Context, in *ConvertWithSnapshotRequest, opts ...grpc.CallOption) (*ConvertAmountResponse, error)
}

type fxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFxServiceClient(cc grpc.ClientConnInterface) FxServiceClient {
	return &fxServiceClient{cc}
}

func (c *fxServiceClient) CaptureRateSnapshot(ctx context.Context, in *CaptureRateSnapshotRequest, opts ...grpc.CallOption) (*CaptureRateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureRateSnapshotResponse)
	err := c.cc.Invoke(ctx, FxService_CaptureRateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxServiceClient) ConvertAmount(ctx context.Context, in *ConvertAmountRequest, opts ...grpc.CallOption) (*ConvertAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertAmountResponse)
	err := c.cc.Invoke(ctx, FxService_ConvertAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxServiceClient) ConvertWithSnapshot(ctx context.Context, in *ConvertWithSnapshotRequest, opts ...grpc.CallOption) (*ConvertAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertAmountResponse)
	err := c.cc.Invoke(ctx, FxService_ConvertWithSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FxServiceServer is the server API for FxService service.
// All implementations must embed UnimplementedFxServiceServer
// for forward compatibility.
type FxServiceServer interface {
	CaptureRateSnapshot(context.Context, *CaptureRateSnapshotRequest) (*CaptureRateSnapshotResponse, error)
	ConvertAmount(context.Context, *ConvertAmountRequest) (*ConvertAmountResponse, error)
	ConvertWithSnapshot(context.Context, *ConvertWithSnapshotRequest) (*ConvertAmountResponse, error)
	mustEmbedUnimplementedFxServiceServer()
}

// UnimplementedFxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFxServiceServer struct{}

func (UnimplementedFxServiceServer) CaptureRateSnapshot(context.Context, *CaptureRateSnapshotRequest) (*CaptureRateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureRateSnapshot not implemented")
}
func (UnimplementedFxServiceServer) ConvertAmount(context.Context, *ConvertAmountRequest) (*ConvertAmountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertAmount not implemented")
}
func (UnimplementedFxServiceServer) ConvertWithSnapshot(context.Context, *ConvertWithSnapshotRequest) (*ConvertAmountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertWithSnapshot not implemented")
}
func (UnimplementedFxServiceServer) mustEmbedUnimplementedFxServiceServer() {}
func (UnimplementedFxServiceServer) testEmbeddedByValue()                   {}

// UnsafeFxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FxServiceServer will
// result in compilation errors.
type UnsafeFxServiceServer interface {
	mustEmbedUnimplementedFxServiceServer()
}

func RegisterFxServiceServer(s grpc.ServiceRegistrar, srv FxServiceServer) {
	// If the following call panics, it indicates UnimplementedFxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FxService_ServiceDesc, srv)
}

func _FxService_CaptureRateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).CaptureRateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FxService_CaptureRateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).CaptureRateSnapshot(ctx, req.(*CaptureRateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxService_ConvertAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).ConvertAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FxService_ConvertAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).ConvertAmount(ctx, req.(*ConvertAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxService_ConvertWithSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertWithSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).ConvertWithSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FxService_ConvertWithSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).ConvertWithSnapshot(ctx, req.(*ConvertWithSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FxService_ServiceDesc is the grpc.ServiceDesc for FxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fx.FxService",
	HandlerType: (*FxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CaptureRateSnapshot",
			Handler:    _FxService_CaptureRateSnapshot_Handler,
		},
		{
			MethodName: "ConvertAmount",
			Handler:    _FxService_ConvertAmount_Handler,
		},
		{
			MethodName: "ConvertWithSnapshot",
			Handler:    _FxService_ConvertWithSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fx.proto",
}
